cores/rp2040/stdlib_noniso.cpp
cores/rp2040/stdlib_noniso.h

Borrowed from https://github.com/esp8266/Arduino , include dtostrf() and
others.
Fixes #13

Add non-standard library calls used by String

---

cores/rp2040/Arduino.h
cores/rp2040/wiring_private.cpp

Add attach/detachInterrupt support

---

cores/rp2040/wiring_private.cpp

The Pico SDK only supports a single callback pointer for all GPIO
interrupt pins.  So we need to track the individual pin-to-CB map
ourselves and dispatch from our own internal callback routine.
Fixes #25

Fix attachInterrupt to handle single GPIO callback

---

libraries/Wire/Wire.cpp
libraries/Wire/Wire.h
libraries/Wire/examples/TalkingToMyself/TalkingToMyself.ino

Also fix the initial pins for the 2nd I2C interface onboard.

Add I2C slave support and include a simple example

---

package/package_pico_index.template.json

Add Raspberry Pi binaries, OpenOCD, and new boards

---

cores/rp2040/Arduino.h

Add NOT_AN_INTERRUPT define

---

cores/rp2040/Tone.cpp

Add a mutex around the Tone mapping for multicore safety.

Make Tone multicore safe

---

tools/uf2conv.py

Look for UF2 drives in additional spots on Linux

---

platform.txt

Make the link process less insane.  Not sane, just less insane.

Rationalize link stage command line

---

tools/uf2conv.py

Ignore non-UTF8 chars in UF2 upload

---

cores/rp2040/Arduino.h

As mentioned in https://github.com/earlephilhower/arduino-pico/discussions/156#discussion-3376456

Add quasi-sane abs() implementation to Arduino.h

---

.github/workflows/pull-request.yml
cores/rp2040/RP2040USB.cpp
cores/rp2040/SerialUSB.cpp
cores/rp2040/SerialUSB.h
cores/rp2040/Tone.cpp
cores/rp2040/posix.cpp
cores/rp2040/wiring_analog.cpp
cores/rp2040/wiring_digital.cpp
cores/rp2040/wiring_private.cpp
cores/rp2040/wiring_pulse.cpp
cores/rp2040/wiring_shift.cpp
libraries/I2S/src/I2S.cpp
libraries/SPI/SPI.cpp
libraries/Wire/Wire.cpp
libraries/rp2040/examples/Time/Time.ino
tests/astyle_core.conf
tests/astyle_examples.conf
tests/build.sh
tests/ci/build_boards.sh
tests/ci/build_docs.sh
tests/ci/build_package.sh
tests/ci/host_test.sh
tests/ci/pkgrefs_test.sh
tests/ci/style_check.sh
tests/common.sh
tests/debug.sh
tests/restyle-examples-only.sh
tests/restyle.sh
tests/run_CI_locally.sh
tools/build.py

Add compilation to CI

---

docs/usb.rst

Add TinyUSB usage note.

---

cores/rp2040/wiring_digital.cpp

Set GPIO digital output on digitalWrite

---

cores/rp2040/Arduino.h

Many functions are defined inside the api/Common.h, so remove them from
the Arduino.h header to have them appear only once.
Fix up the abs() macro to avoid macro problems, add round()

Clean up Arduino.h header, remove duplicates

---

cores/rp2040/wiring_pulse.cpp

Fix pulseIn detection

---

variants/challenger_2040_wifi/pins_arduino.h

Adding definitions for internal reset and mode pins for ESP8285.

Update pins_arduino.h for challenger_2040_wifi

---

variants/generic/common.h

Fixes #368.  Thanks @bperrybap!

Add SDA/SCL variables like other cores export

---

variants/arduino_nano_connect/pins_arduino.h

Fix issues with [WiFiNINA](https://github.com/arduino-libraries/WiFiNINA) and [WiFiNINA_Generic](https://github.com/khoih-prog/WiFiNINA_Generic) libraries
- [#373](https://github.com/earlephilhower/arduino-pico/issues/373)
- [#375](https://github.com/earlephilhower/arduino-pico/issues/375)
- [#376](https://github.com/earlephilhower/arduino-pico/issues/376)

Fix Nano_RP2040_Connect issue

---

cores/rp2040/SerialPIO.cpp
cores/rp2040/SerialUART.cpp

When the Serial software FIFOs overeflowed, the IRQ handler would not
read any more data from the hardware FIFOs.  This would cause the
IRQ handler to be continually called as soon as it exited since the
HW FIFOS were not empty.
Now always read every available HW FIFO entry and throw out any that
don't fit in the SW FIFO.
Also fix a too long by half stop bit timing in the PIOSerial receiver.

Fix hang on Serial overflow, PIOSerial stop bit handling

---

variants/adafruit_feather/pins_arduino.h
variants/adafruit_itsybitsy/pins_arduino.h
variants/adafruit_qtpy/pins_arduino.h

Hello. I'm one of the Adafruit folks. I'm submitting a PR to add the NeoPixel pins to three of our boards. Thanks!

Adding NeoPixel pins.

---

cores/rp2040/api/deprecated-avr-comp/avr/pgmspace.h

Fix pgm_read_ macros with inline functions

---

libraries/Wire/src/Wire.cpp

Allow changing I2C clock speed while running

---

docs/ide.rst

Document the Generic RP2040 option

---

cores/rp2040/SerialPIO.cpp
cores/rp2040/SerialPIO.h
cores/rp2040/SerialUART.cpp
cores/rp2040/SerialUART.h

Matching the Arduino SoftwareSerial API

Add ::overflow() return to SerialUART/SerialPIO

---

docs/conf.py
docs/freertos.rst
docs/index.rst

Alabaster is not my favorite, try something with colors...

Change the RTD theme

---

cores/rp2040/SerialPIO.h
cores/rp2040/SoftwareSerial.h

Add invert option to SWSerial

---

libraries/FreeRTOS/src/FreeRTOSConfig.h

Fix compile error when configSUPPORT_STATIC_ALLOCATION is set to 1

---

package/build_boards_manager_package.sh
platform.txt

Need to munge the platform.txt on release.
Fixes #576

Fix picoprobe and pico-debug upload recipes

---

cores/rp2040/SerialPIO.cpp

Fixes #593
When SerialPIO::end is called, stop the PIO SMs and potentially
disable the IRQ handler if this is the last RX port on that PIO.

Deallocate resources on SerialPIO::end

---

libraries/Wire/src/Wire.cpp

Disable Wire slave interrupt on ::end

---

docs/analog.rst

Add support for analogReadResolution, default 10b 
https://github.com/earlephilhower/arduino-pico/pull/461

add analogReadResolution() docs

---

tests/build-tinyusb.sh

Update to latest Adafruit_TinyUSB

---

platform.txt

Fixes #643 .   Thanks @VisualMicro

Add dependency file generation to build

---

.github/workflows/release-to-publish.yml

Need to manually list the secrets to export to the environment.

Actually pass in the PIO key for auto-publishing

---

docs/digital.rst
docs/pins.rst

- moved Pad Strength from pins.rst to digital.rst
- add information about input modes

docs gpio (digital.rst)

---

package/package_pico_index.template.json
tools/makeboards.py

Keep the Arduino Board Manager list up-to-date from makeboards.py

Automatically update the JSON file in makeboards

---

cores/rp2040/sdkoverride/cyw43_arch_threadsafe_background.c

Provide dummy CYW43 callbacks when no WiFi used

---

libraries/WiFi/src/WiFiClass.cpp

Make AP mode report WL_CONNECTED

---

tools/platformio-build.py

Ref: https://github.com/earlephilhower/arduino-pico/pull/717#issuecomment-1197921851

Add CMSIS defines to Platform.io

---

boards.txt
package/package_pico_index.template.json
tools/json/seeed_xiao_rp2040.json
tools/makeboards.py

https://github.com/maxgerhardt/platform-raspberrypi/pull/12

Fix typo in XIAO board name

---

.github/workflows/pull-request.yml
libraries/LEAmDNS/keywords.txt
libraries/MD5Builder/library.properties
libraries/Updater/library.properties
libraries/WiFi/library.properties
tools/platformio-build.py

Partial #754
Add the boodloader blob to the Platform.IO link

Add OTA.O to make p.io builds function

---

cores/rp2040/FS.h
docs/ide.rst
docs/install.rst
docs/wifi.rst
libraries/I2S/src/I2S.h
libraries/LEAmDNS/src/LEAmDNS.h
libraries/LEAmDNS/src/LEAmDNS_Control.cpp
libraries/WiFi/src/WiFiClientSecureBearSSL.cpp
libraries/WiFi/src/wl_definitions.h
libraries/rp2040/examples/Bootsel/Bootsel.ino

Avoid spurious -O3 warning

---

libraries/WiFi/src/WiFiClass.h

Add ESP8266 compat functions for AP mode

---

libraries/EEPROM/EEPROM.h

EEPROM: Add an update function

---

libraries/DNSServer/keywords.txt
libraries/DNSServer/library.properties
libraries/DNSServer/src/DNSServer.cpp
libraries/DNSServer/src/DNSServer.h
libraries/WiFi/src/dhcpserver/dhcpserver.c

Add a simple DNS server for AP mode

Port ESP8266 DNSServer

---

docs/rp2040.rst

Very small change, but just for completeness I thought I'd just add the missing stuff right now.

Fix functions in docs: RP2040 Helper Class

---

libraries/WebServer/src/HTTPServer.cpp

Don't try and heap allocate temporaty <16b chunks.

Remove microscopic malloc() from WebServer

---

libraries/WebServer/src/detail/mimetable.h

Decreases WebServer sketch sizes.

Shrink MIME table flash usage by ~500 bytes

---

cores/rp2040/api/HardwareSPI.h
libraries/SPI/src/SPI.cpp
libraries/SPI/src/SPI.h

Should speed up SD transfers significantly.
See #801

Add bidirectional bulk SPI transfer, update SdFAT

---

cores/rp2040/SerialUART.cpp
cores/rp2040/SerialUART.h

Restore GPIO functions on SerialUART::end

---

libraries/FreeRTOS/examples/StaticMulticore-FreeRTOS/StaticMulticore-FreeRTOS.ino
libraries/FreeRTOS/src/FreeRTOSConfig.h

Enabled static memory allocation with example

---

variants/cytron_maker_pi_rp2040/pins_arduino.h

Update Cytron Pico SPI pinout

---

boards.txt
platform.txt
tools/makeboards.py
variants/rpipicow/picow_init.cpp

Allow setting the WiFi region for PicoW

---

cores/rp2040/wiring_private.cpp

Fix deadlock during attachInterrupt

---

cores/rp2040/SerialUART.cpp

Allow setCTS/RTS(UART_PIN_NOT_DEFINED)

---

cores/rp2040/CoreMutex.cpp

Fix Serial1/2 debug output mode in CoreMutex

---

cores/rp2040/Tone.cpp

Drive pin LOW after Tone(period) timeout

---

platform.txt

Fixes #896 since it seems the Arduino.cc core defines this constant

Add TARGET_RP2040 to build defines

---

libraries/WebServer/examples/AdvancedWebServer/AdvancedWebServer.ino

Un-hardcode LED pin in AdvancedWebServer example

---

libraries/WebServer/examples/AdvancedWebServer/AdvancedWebServer.ino
libraries/WebServer/src/HTTPServer.cpp

Fix memory leak in WebServer

---

cores/rp2040/wiring_private.cpp

noInterrupts/interrupts use a stack to allow multiple calls to work properly.  The original code was using a std::stack which will use malloc() to allocate entry space.  This seems like a bad idea, and makes it so it's impossible to disable interrupts for malloc/free, etc.
Define a fixed stack size and use straight C code to manage the IRQ stacks.  Slightly more fixed memory requirements, but significantly lower total RAM requirements and no malloc() dependency.

Use static allocation for IRQ stack

---

libraries/WiFi/src/WiFiClass.cpp

Added a way to return the RSSI value as shown in this thread:
https://forums.raspberrypi.com/viewtopic.php?t=341774

Add a way to return the RSSI value

---

cores/rp2040/RP2040Support.h
libraries/ArduinoOTA/src/ArduinoOTA.cpp
libraries/WiFi/src/WiFiClass.cpp
libraries/WiFi/src/WiFiClass.h

This PR:
1. Fixes buffer overflow in getChipId
2. Adds support for asynchronous WiFi scanning
3. Fixes some ESP compatibility issues
4. Fixes SSID() so that a copy of SSID name is kept inside WiFi class. In case the original value is deleted

Async scan + bugfixes

---

cores/rp2040/SerialPIO.cpp

Free PIO SM on SerialPIO::end

---

boards.txt
tools/json/arduino_nano_connect.json
tools/makeboards.py

Fix Arduino Nano Connect USB VID:PID tuples

---

libraries/Wire/src/Wire.cpp

Merge in changes @chrisckc debugged while working at 400khz on his own project. See https://github.com/earlephilhower/arduino-pico/issues/979#issuecomment-1328237128

Update Wire per @chrisckc debugging

---

boards.txt
tools/makeboards.py

Supersedes #972.  Thanks @kholk

Allow building w/o USB for normal and picoprobe builds

---

cores/rp2040/Arduino.h
keywords.txt

Add digitalWrite/ReadFast macros

---

cores/rp2040/wiring_analog.cpp
cores/rp2040/wiring_digital.cpp

Only change the ADC mux/GPIO control when things re not yet set up. See #1070

Speed up ADC reads by not re-initting

---

libraries/I2S/src/AudioRingBuffer.cpp
libraries/I2S/src/AudioRingBuffer.h
libraries/I2S/src/I2S.h

Also clean up unneeded includes for I2S

Fix I2S::flush volatile casting

---

cores/rp2040/WString.h

Add WString.h include redirect for broader compat

---

cores/rp2040/Arduino.h

Pull request as discussed in https://github.com/earlephilhower/arduino-pico/issues/1086

Adding sei() and cli() as aliases for interrupts() and noInterrupts().

---

cores/rp2040/Tone.cpp
cores/rp2040/wiring_analog.cpp
libraries/LittleFS/src/LittleFS.h
libraries/SPI/src/SPI.cpp
libraries/Updater/src/Updater.cpp
libraries/WiFi/src/WiFiMulti.cpp
libraries/WiFi/src/include/ClientContext.h

Exposed by #1090, remove ugly printf format warnings while in debug mode

Remove debug printout warnings

---

docs/i2s.rst
libraries/I2S/keywords.txt
libraries/I2S/src/I2S.cpp
libraries/I2S/src/I2S.h
libraries/I2S/src/pio_i2s.pio
libraries/I2S/src/pio_i2s.pio.h

Add LSBJ format support for I2S

---

docs/pwm.rst
libraries/AudioBufferManager/src/AudioBufferManager.cpp
libraries/PWMAudio/src/PWMAudio.cpp
libraries/PWMAudio/src/PWMAudio.h

Also fix crash on PWMAudio::end()

Allow on-the-fly changes to PWMAudio when possible

---

libraries/Wire/src/Wire.cpp

Handle slave mode I2C restarts

---

libraries/WebServer/examples/HelloServer/HelloServer.ino
libraries/WebServer/src/HTTPServer.cpp
libraries/WebServer/src/HTTPServer.h
libraries/WebServer/src/Parsing.cpp

Implement the method used in the ESP8266 Web Server to allow user apps to hook into the HTTP server (to support hooked WebSockets, etc._)
Add example of hook usage

Add hook support to WebServer

---

cores/rp2040/SerialUART.cpp

Fix SerialUART::overflow reporting race condition

---

libraries/WiFi/src/WiFiClass.h

Add ESP8266/32 WiFi.isConnected wrapper

---

libraries/SD/src/SD.h

Pull in the portion of the change correcting the flag setting from https://github.com/esp8266/Arduino/pull/8833

Apply SD.h fix from ESP8266

---

libraries/WiFi/src/WiFiClass.cpp

Implement WiFi::softAPgetStationNum

---

libraries/SD/examples/Datalogger/Datalogger.ino
libraries/SD/examples/DumpFile/DumpFile.ino
libraries/SD/examples/Files/Files.ino
libraries/SD/examples/ReadWrite/ReadWrite.ino
libraries/SD/examples/listfiles/listfiles.ino

Update SD examples with working SPI configs

---

cores/rp2040/RP2040Support.h
docs/rp2040.rst

Per question received via email.

Add rp2040.cpuid() call to get running core

---

tools/uf2conv.py

Without flushing STDOUT, the upload script's output aften are buffered and not displayed until it completes.  Add in flush commands to allow the IDE to display status as it changes.

Make uf2conf.py flush STDOUT for real-time updates

---

package/package_pico_index.template.json

Includes fixes for ::printf/etc. using stdout/stderr Fixes #1181

Upgrade to toolchain 1.5.0-b

---

package/build_boards_manager_package.sh

Add release package fixups for picoprobe-cmsis-dap

---

boards.txt
tools/makeboards.py

BLE tested working with BTStack BLE hog-keyboard-demo.

Fix BLE enable definition

---

platform.txt

Fic for https://github.com/earlephilhower/arduino-pico/issues/1249

Update platform.txt - Fix for #1249

---

tools/platformio-build.py

I went for a similar definition to the IPv6 one, `PIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH`

Add bluetooth support to Platform.io

---

variants/waveshare_rp2040_lcd_1_28/pins_arduino.h

Tested and verified on my hardware.

Fix pin assigment for Waveshare RP2040 1.28 LCD PIN_BAT_ADC

---

libraries/BTstack/README.rp2040
libraries/BTstack/examples/ANCS/ANCS.ino
libraries/BTstack/examples/LECentral/LECentral.ino
libraries/BTstack/examples/LEPeripheral/LEPeripheral.ino
libraries/BTstack/examples/iBeacon/iBeacon.ino
libraries/BTstack/examples/iBeaconScanner/iBeaconScanner.ino
libraries/BTstack/keywords.txt
libraries/BTstack/library.properties
libraries/BTstack/src/BTstack.cpp
libraries/BTstack/src/BTstack.h
tests/restyle.sh

The BTstack driver includes a basic Arduino library as part of the ports directory.

Add (unsupported) BTstack Arduino library

---

README.md

Adds some notes to the README to point out flatpak issues and a workaround.

Add flatpak-specific instructions

---

cores/rp2040/RP2040USB.cpp
cores/rp2040/RP2040USB.h
cores/rp2040/sdkoverride/tusb_absmouse.h
libraries/MouseAbsolute/README.adoc
libraries/MouseAbsolute/docs/api.md
libraries/MouseAbsolute/docs/readme.md
libraries/MouseAbsolute/examples/CircleAbsolute/CircleAbsolute.ino
libraries/MouseAbsolute/keywords.txt
libraries/MouseAbsolute/library.properties
libraries/MouseAbsolute/src/MouseAbsolute.cpp
libraries/MouseAbsolute/src/MouseAbsolute.h
libraries/MouseBLE/examples/BLECircleAbsolute/BLECircleAbsolute.ino
libraries/MouseBLE/src/MouseBLE.cpp
libraries/MouseBLE/src/MouseBLE.h
libraries/MouseBT/examples/BTCircleAbsolute/BTCircleAbsolute.ino
libraries/MouseBT/keywords.txt
libraries/MouseBT/src/MouseBT.cpp

Fixes #1338
To be revisited when TinyUSB native support is added and picked up in the SDK

Add absolute mouse support

---

docs/platformio.rst

Per title.
Documents the solutions for issues such as #1349.

Add BTC and BLE docs to PlatformIO

---

docs/install.rst

Add MacOS Picotool upload help

---

libraries/WiFi/examples/BearSSL_CertStore/certs-from-mozilla.py

See https://github.com/esp8266/Arduino/pull/8907

Don't delete first cert, taken from ESP8266 repo

---

libraries/FreeRTOS/keywords.txt
libraries/FreeRTOS/src/variantHooks.cpp
variants/generic/common.h

FreeRTOS compilation fix when no LED present

---

docs/install.rst

This PR adds instructions to install this core using Arduino CLI.

Add Arduino CLI installation instructions

---

libraries/SerialBT/examples/BTSerialUppercase/BTSerialUppercase.ino

Hello Mr Philhower.
I completed the comments of BTSerial with a Mac
Best regards

BT Serial connection with Mac

---

variants/adafruit_feather/pins_arduino.h

BREAKING: Swap Wire1 and Wire in Adafruit Feather

---

.github/workflows/release-to-publish.yml

See RPI's CEO comment https://github.com/platformio/platform-raspberrypi/pull/36#issuecomment-1560504425

Temporary disable publishing to the PIO registry

---

cores/rp2040/CoreMutex.cpp
cores/rp2040/_freertos.h
libraries/FreeRTOS/src/variantHooks.cpp

This is the PR related to https://github.com/earlephilhower/arduino-pico/issues/1470.
Did basic testing but not yet tested all possibilities regarding usage in isr.
Will only be able to do that from June 5 onwards (short break).

CoreMutex freeRTOS Mutex acquiring

---

libraries/I2S/src/I2S.cpp

Return the actual number of samples that can be read/written, not the number of 32-bit values there is space for.

Fix I2s::available/availableForWrite()

---

docs/i2s.rst
libraries/I2S/src/I2S.h

Add I2S::getOverUnderflow()

---

libraries/I2S/src/I2S.cpp

Per the Arduino documentation, I2s::available should return bytes free, not samples.  Adjust accordingly.

I2S::available/availableForWrite() returns bytes

---

cores/rp2040/RP2040Support.h

add 	function rebootToBootloader()

Update RP2040Support.h -> add function to reboot to bootloader from code

---

libraries/I2S/src/I2S.cpp

Per https://github.com/earlephilhower/arduino-pico/pull/1524#issuecomment-1587562257

Call I2S::end() in I2S destructor

---

libraries/I2S/src/I2S.cpp

Per https://github.com/earlephilhower/arduino-pico/pull/1524#issuecomment-1587885054

I2S check for failure of ARB and PIO allocation

---

libraries/lwIP_Ethernet/src/LwipIntfDev.h

Remove leftover debug printf in LWIP_Ethernet

---

docs/ota.rst
libraries/HTTPUpdate/src/HTTPUpdate.cpp

Remove obsolete refs to ATOMIC_FS_UPDATE

---

libraries/Updater/src/Updater.cpp

Thanks to @pietglas for finding and fixing.  See #1590 for more info.

Fix FS upload crash

---

variants/generic/common.h

Fix for missing dependency on uint8_t types

add stdint.h to common.h. Fix issue #1676.

---

platform.txt

Avoid obsolete GCC 7.1 note on building WiFi

---

libraries/SPI/src/SPI.cpp

It would be possible for an IRQ-driven SPI user to fire while the main app's SPI.beginTransaction was in process. This would result in incorrect state for the main app since the IRQ may overwrite some settings that the app already set.
Disable all IRQs around the begin and end processes to avoid the possibility.

Protect SPI transaction start/end from race conditions

---

libraries/BTstackLib/src/BTstackLib.h
tests/common.sh

Per https://github.com/bluekitchen/btstack/issues/529#issuecomment-1746293987

Mark the BTStackLib as unsupported

---

libraries/BTstackLib/src/BTstackLib.h
tests/common.sh

Undo BSTstackLib warning

---

libraries/lwIP_enc28j60/src/utility/enc28j60.cpp
libraries/lwIP_w5500/src/utility/w5500.h

Protect W5500/ENC28J60 isLinked from periodic interrupt

---

cores/rp2040/RP2040Support.h
cores/rp2040/main.cpp

as discussed in ticket #1814 , a suggestion for optimizing batch processing for core1 incl matching helper functions.
i tried to adopt your naming scheme. but feel free to customize it if you don't like it.
i hope this is as you envisioned it.

optimizes core1 stack handling

---

libraries/WiFi/src/WiFiMulti.cpp
libraries/WiFi/src/WiFiMulti.h

Made change for "Feature Request: Clear AP List in WiFiMulti #1846" by adding clearAPList method to WiFiMulti.

Added clearAPList method to WiFiMulti

---

docs/analog.rst

Fix small typo in analog.rst

---

libraries/SPI/keywords.txt
libraries/SPI/src/SPI.cpp

Fix SPI 16-bit transfers

---

docs/platformio.rst

Hi,
Just a couple of corrections - a typo and a superfluous newline (as it seemed to me at least) in the PlatformIO documentation.

Minor documentation corrections in platformio.rst.

---

libraries/SD/src/SD.h
libraries/SDFS/src/SDFS.h

#1893 SD.h wrong calculation of totalBlocks

correct calculation of totalBlocks() in SD.h and SDFS.h

---

libraries/FreeRTOS/src/variantHooks.cpp

Undo FreeRTOS idle task changes

---

package/package_pico_index.template.json

Update Windows Picotool blob pointers

---

libraries/SD/src/SD.h

Use passed-in SPI on SD.end(true)

---

cores/rp2040/SerialUART.cpp

Unswap CTS/RTS enable on SeriaUART

---

docs/ota.rst

Hi,
Just a typo and a couple of wording corrections.

Minor corrections to ota.rst

---

docs/piouart.rst

Hi,
Added a newline so that code block is displayed correctly.

Fixed code block in piouart.rst.

---

libraries/lwIP_Ethernet/examples/EthernetLibCompatible/EthernetLibCompatible.ino
libraries/lwIP_Ethernet/src/EthernetCompat.h

Ethernet legacy API compatibility layer EthernetCompat.h is from esp8266 core.
The example is from the Arduino Ethernet library with include changed and Ethernet object instance created.
For cases like this https://github.com/earlephilhower/arduino-pico/issues/2129#issuecomment-2081217703

Ethernet legacy API compatibility layer

---

libraries/SerialBT/examples/BTSerialUppercase/BTSerialUppercase.ino
libraries/SerialBT/keywords.txt
libraries/SerialBT/src/SerialBT.cpp
libraries/SerialBT/src/SerialBT.h

Allow setting SerialBT advertised name

---

libraries/HTTPClient/src/HTTPClient.cpp

From https://github.com/espressif/arduino-esp32/pull/8713

HTTPClient - Fix case sensitivity for header keys

---

libraries/NetBIOS/src/NetBIOS.cpp

Instead of manually iterating over netifs to find the one a packet came in over for NetBIOS name resolution, use a built-in LWIP callback that's available for udp_recv callbacks.  Shrinks and simplifies NetBIOS code.

Use built-in LWIP call to determine NetBIOS IP

---

libraries/BTstackLib/src/BTstackLib.cpp
libraries/BTstackLib/src/BTstackLib.h

Receive GATT characteristic updates in BTStackLib

---

libraries/Ticker/examples/Blinker/Blinker.ino
libraries/Ticker/examples/TickerBasic/TickerBasic.ino
libraries/Ticker/examples/TickerParameter/TickerParameter.ino
libraries/Ticker/keywords.txt
libraries/Ticker/library.properties
libraries/Ticker/src/Ticker.cpp
libraries/Ticker/src/Ticker.h
tests/restyle.sh

Uses the Pico SDK alarms and repeated-timers to provide for IRQ-level periodic tasks to be scheduled.

Add ESP32-compatible Ticker library

---

libraries/FreeRTOS/tests/README.md
libraries/FreeRTOS/tests/freertos_reent/freertos_reent.ino
libraries/FreeRTOS/tests/freertos_syscallmutex/freertos_syscallmutex.ino

FreeRTOS often seems to have interesting corner cases.  Add two simple tests that have been useful while debugging issues found from users or from FreeRTOS updates.

Add FreeRTOS functionality tests

---

libraries/WebServer/src/HTTPServer.h
libraries/WebServer/src/Parsing.cpp
libraries/WebServer/src/WebServerTemplate.h

Upstream patch https://github.com/espressif/arduino-esp32/pull/9991

Fix timeout in WebServer::_uploadReadByte and handleClient()

---

.github/workflows/pull-request.yml
.github/workflows/release-to-publish.yml
.github/workflows/tag-to-draft-release.yml
tests/build-tinyusb.sh
tests/build.sh
tests/ci/build_boards.sh
tests/ci/build_docs.sh
tests/ci/build_package.sh
tests/ci/host_test.sh
tests/ci/style_check.sh
tests/common.sh
tests/debug.sh
tests/run_CI_locally.sh

Remove obsolete TRAVISCI variables

---

package/package_pico_index.template.json

Attempt to make IDE really downloade SDK 2.0.0 tools

---

boards.txt
package/package_pico_index.template.json
tools/json/cytron_iriv_io_controller.json
tools/makeboards.py
variants/cytron_iriv_io_controller/pins_arduino.h

Please help to add new board variant for RP2350.
https://www.cytron.io/p-iriv-io-controller
Thank you.

Add new board: IRIV IO Controller.

---

cores/rp2040/SerialPIO.cpp

New IRQs and PIO pointers required for the 3rd PIO on the 2350.
Fixes #2447

Support PIO2 for SoftwareSerial/SerialPIO

---

libraries/SPI/src/SPI.cpp
libraries/SPISlave/src/SPISlave.cpp
libraries/Wire/src/Wire.cpp

Fix PICO_RP2350B define check for other peripherals

---

cores/rp2040/Bootsel.cpp
cores/rp2040/sdkoverride/btstack_flash_bank.cpp
libraries/EEPROM/src/EEPROM.cpp
libraries/FreeRTOS/tests/corefreeze/corefreeze.ino
libraries/LittleFS/src/LittleFS.cpp
libraries/Updater/src/Updater.cpp

Fix FreeRTOS Flash Freeze, Fastly

---

libraries/FreeRTOS/src/variantHooks.cpp

`taskENTER_CRITICAL()` and `taskEXIT_CRITICAL()` cannot be used in an interrupt context.
This PR allows the usage of `noInterrupts()` and `interrupts()` inside an interrupt. Libraries that call these functions should now work instead of hanging.

Add ISR check to critical section

---

README.md

Add WIZnet W55RP20-EVB-Pico into README

---

libraries/I2S/examples/SimpleTone/SimpleTone.ino
libraries/I2S/src/I2S.cpp
libraries/I2S/src/I2S.h

Pins are a physical connection, makes sense to define them at construction.

Allow I2S constructor to set pins, like PWMAudio

---

tools/libpico/CMakeLists.txt

Use the distributed ARM ar in libpico, not system

---

.gitmodules
docs/fs.rst
libraries/SD/examples/CardInfo/CardInfo.ino
libraries/SD/examples/Datalogger/Datalogger.ino
libraries/SD/examples/DumpFile/DumpFile.ino
libraries/SD/examples/Files/Files.ino
libraries/SD/examples/ReadWrite/ReadWrite.ino
libraries/SD/examples/listfiles/listfiles.ino
libraries/SD/src/SD.h
libraries/SDFS/src/SDFS.cpp
libraries/SDFS/src/SDFS.h
platform.txt
tests/common.sh
tools/platformio-build.py

Remove ESP8266SdFat fork and replaces with upstream SdFat to simplify things.  This 2.3.0 version adds SDIO support and enables exFAT support. Also moved FAT LFNs to 256 chars, same as LittleFS.

Replace ESP8266SdFat w/SdFat 2.3.0, add SDIO,ExFAT

---

variants/adafruit_feather_rp2350_hstx/pins_arduino.h

Fix I2C on Adafruit Feather RP2350 HSTX

---

libraries/Updater/src/Updater.cpp

Fixes #2785.  Thanks @donmsmall!

OTA Updater better error codes on OOS

---

cores/rp2040/main.cpp
cores/rp2040/psram.cpp
cores/rp2040/psram.h

Adjust the PSRAM clock when over/underclock F_SYS

---

cores/rp2040/IPAddress.h

Fix issue with WiFiNINA includes.  Fixes #2887

Add explicit using arduino::IPAddress to headers

---

libraries/lwIP_w55rp20/examples/WiFiClient-W55RP20/WiFiClient-W55RP20.ino
libraries/lwIP_w55rp20/src/utility/w55rp20.h

Update W55RP20 example for proper CS pin

---

cores/rp2040/Arduino.h

Fix remaining PICO_RP2350B reference

---

libraries/SPI/src/SPI.cpp

Update SPI.cppFix RP2350B SPI RX pin list

---

libraries/BTstackLib/src/BTstackLib.cpp

Fix BSTstackLib service UUID reporting to client

---

libraries/lwIP_Ethernet/src/LwipIntfDev.h

Clear any existing IP before sending a DHCP request

---

variants/adafruit_metro/pins_arduino.h

Add SDIO PIN definitions for Adafruit Metro RP2040

---

libraries/SPISlave/src/SPISlave.cpp
libraries/SPISlave/src/SPISlave.h

Use the SPIHelper class already there for the SPI/SoftwareSPI

Remove duplicated code from SPISlave

---

variants/bigtreetech_SKR_Pico/pins_arduino.h

Remove incorrect definiton opn BTT SKR Pico

---

docs/fs.rst

Note obsolete LittleFS upload limitations

---

docs/bluetooth.rst

I corrected typo in docs/bluetooth.rst for unlockBluetooth.

Changed unlockBluetooth to __unlockBluetooth

---

variants/adafruit_fruitjam/pins_arduino.h

MCLK and word select were swapped

Update I2S for Fruit Jam

---

cores/rp2040/wiring_private.cpp

Restore missing irqStackTop decrement
