earlephilhower/arduino-pico

cores/rp2040/wiring_digital.cpp, libraries/Wire/Wire.cpp, libraries/Wire/Wire.h
Fix the drive logic for pullup and pulldown inputs.
Add a bitbanged I2C ACK checker for 0-byte I2C transfers (since the HW
doesn't support it).
Add a timeout on I2C reads and writes so they don't hang forever if a
device is not present.
Fixes #38
=> Fix INPUT_PULLUP/DOWN, I2C 0-len probes, timeout

tools/uf2conv.py
Sketch upload to serial port fails on macos because the Arduino IDE uses the callout device "/dev/cu". Adding recognition of "/dev/cu" to uf2conv.py makes the sketch upload work.
Addresses #46
=> Recognize /dev/cu in args.serial

cores/rp2040/main.cpp
To allow for uploads when sketches don't manually start the Serial port,
start the USB port always in main().
Fixes #50
=> Always enable USB serial port for reset

libraries/rp2040/keywords.txt
reference: cores/rp2040/wiring_analog.cpp:108:extern "C" float analogReadTemp()
=> correct analogReadTemp KEYWORD

cores/rp2040/Arduino.h
Update the ArduinoAPI with new macros/inlines that allow accessing
values that are not naturally aligned (i.e. an int at address 0x0001).
Fixes #79
=> Allow misaligned pgm_read_XXX macro reads

cores/rp2040/CoreMutex.h, cores/rp2040/Tone.cpp, cores/rp2040/wiring_analog.cpp, cores/rp2040/wiring_private.cpp
Keep a per-core IRQ stack for noInterrupts since each core has its own
enable/disable.
Make analogRead/analogWrite multicore safe
=> More multicore safety plumbing, IRQs, analogXXX

cores/rp2040/SerialUART.cpp, cores/rp2040/SerialUART.h, libraries/SPI/SPI.cpp, libraries/SPI/SPI.h, libraries/Wire/Wire.cpp, libraries/Wire/Wire.h, libraries/Wire/examples/TalkingToMyself/TalkingToMyself.ino, variants/adafruitfeather/pins_arduino.h, variants/generic/common.h, variants/generic/pins_arduino.h, variants/rpipico/pins_arduino.h
Using the official Raspberry Pi Pico datasheet and the Adafruit Feather
RP2040 schematic, set the default pins for peripherals to match.
Fixes #92
=> Set default pins for peripherals per datasheet

cores/rp2040/main.cpp, docs/index.rst, docs/multicore.rst, libraries/rp2040/examples/Multicore/Multicore.ino
Support running code on the second core by adding a setup1() and/or
a loop1() routine to a sketch.  These functions operate exactly like
the normal Arduino ones, and anything they call will be run on
the second core automatically.
Add a simple multicore example.
=> Add multicore support with setup1/loop1

cores/rp2040/Bootsel.cpp, cores/rp2040/RP2040.h, cores/rp2040/main.cpp
BOOTSEL needs to be multicore protected, too.
Reading BOOTSEL required disabling the flash interface, so the other
core needs to be idles while this runs.
Make the PIO program object multicore safe, too, so that if both cores
try to load a program they won't step on each other.
=> Additional multicore fixes, BOOTSEL and PIO

cores/rp2040/Printable.h
User requested SafeString library support be added for this project.
https://forum.arduino.cc/t/libraries-updated-to-support-new-rp2040-based-boards-raspberry-pi-pico-etc/860353/3
Current SafeString library works for Arduino Mbed OS RP2040 V2.0.0 board install
This pull request fixes missing Printable.h file
But in order to complete adding the support need a unique define (-D... = .. ) that can be detected by SafeString.h so that the
necessary 
namespace arduino {
can be set
Arduino Mbed OS RP2040 V2.0.0 has a -DARDUINO_ARCH_MBED_RP2040  define
Can you add a -D to your compile line (and when Arduino detects libraries)
Also dtostrf( ) declaration not found by SafeString library (works with Arduino pico, fixed by an extern ... in SafeString.h )
=> SF_printable_fix

cores/rp2040/Arduino.h
Per #130 request, the dtostrf() definition and others were not visible.
=> Add stdlib_noniso.h to Arduino.h

variants/generic/common.h
Should fix #134 .  The SPI pin macros were set using the SPI1 set, not
the SPI0 set of pins it should have been using.
=> Fix SPI default pinouts to SPI0, not SPI1 pins

cores/rp2040/main.cpp
Was required before due to C++ internals, but is not needed anymore thanks
to #137
=> Remove hack sync__synchronize from main.cpp

platform.txt
Add -DBOARD_NAME="{build.board}" to Compile patterns to facilitate using BOARD_NAME in sketches
For example
```
void setup() 
{ 
// Open serial communications and wait for port to open:
Serial.begin(115200);
while (!Serial);
Serial.print("Ethernet Test on "); Serial.println(BOARD_NAME);
}
void loop() 
{
}
```
to print
```
Ethernet Test on RASPBERRY_PI_PICO
```
=> Add -DBOARD_NAME="{build.board}"

cores/rp2040/Arduino.h
Add to `Arduino.h` definitions for compatibility to many platforms and libraries
- clockCyclesPerMicrosecond()
- clockCyclesToMicroseconds(a)
- microsecondsToClockCycles(a)
---
All other platforms (see attached list) provide those macros. Without these definitions, we'll get compiler errors when using many libraries.
```
hardware/samd/1.6.8/cores/arduino/Arduino.h:#define microsecondsToClockCycles(a) ( (a) * (SystemCoreClock / 1000000L) )
adafruit/hardware/nrf52/0.21.0/cores/nRF5/Arduino.h:#define microsecondsToClockCycles(a) ( (a) * (SystemCoreClock / 1000000L) )
arduino/hardware/samd/1.8.11/cores/arduino/Arduino.h:#define microsecondsToClockCycles(a) ( (a) * (SystemCoreClock / 1000000L) )
arduino/hardware/avr/1.8.3/cores/arduino/Arduino.h:#define microsecondsToClockCycles(a) ( (a) * …
```
=> Add defs for compatibility

cores/rp2040/main.cpp
Removed needed header from main.cpp during prior cleanup.  Re-add.
Fixes #146
=> Fix over/underclock support

tools/uf2conv.py
Fixes #27
As @vslinuxdotnet discovered, sometimes the RPI firmware update emulated USB
stick does not get automounted under Linux.  Add logic to attempt to use
standard tools to mount it to the uploader, only tried if no drives are
detected normally.
=> Try to mount RPI drive if not already present

.github/workflows/tag-to-draft-release.yml, package/build_boards_manager_package.sh, package/upload_release.py
Ensure no stray files get sucked into the release ZIP by using a clean CI
image to build the package and JSON file.  Auto-populate the draft with
the git commits since the last release.
=> Use CI to build draft releases on a tag push

libraries/EEPROM/EEPROM.cpp, libraries/I2S/src/I2S.cpp, libraries/LittleFS/src/LittleFS.cpp, libraries/SD/src/SD.cpp, libraries/SPI/SPI.cpp, libraries/Servo/src/Servo.cpp, libraries/Wire/Wire.cpp
Fixes #167
For Serial when selecting TinyUSB.  Can't include in the core because Arduino IDE
will not link in libraries called from the core.  Instead, add the header to all
the standard libraries in the hope it will still catch some user cases where they
use these libraries.
See https://github.com/earlephilhower/arduino-pico/issues/167#issuecomment-848622174
=> Add TinyUSB include to all libs

cores/rp2040/SerialUART.cpp, libraries/SPI/SPI.cpp, libraries/Wire/Wire.cpp
Fixes #169
Trying to change pinout while running, or to an illegal configuration,
will now immediately panic() with an error message.  Such an attempt
is a pretty big problem since pinouts are hardware related/static.
Prior code would fail silently and return false, but nobody checked
the setXXX return values, anyway.
=> PANIC on attempting an invalid setXXX pin

libraries/SD/library.properties
When multiple libraries contain files matching an `#include` directive in the program, the Arduino build system must pick one to use for compilation. Multiple factors are used in order to make an intelligent determination of which library is best, as documented [here](https://arduino.github.io/arduino-cli/dev/sketch-build-process/#dependency-resolution).
In order to enhance this determination, the closeness of match between [the library.properties `name` value](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) and the filename in the `#include` directive is being added as one of those factors. This new factor is referred to as [**"Library Name Priority"**](https://arduino.github.io/arduino-cli/dev/sketch-build-process/#library-name-priority) …
=> Use optimal bundled library names

cores/rp2040/Tone.cpp, libraries/rp2040/examples/ToneHappyBirthday/ToneHappyBirthday.ino
this pr fix mutex issue when calling tone() on the same pin with different frequency/duration e.g
- tone(pin, 100, 1000) then
- tone(pin, 100, 2000) it will then call noTone(pin) first before create the new Tone object
The issue is mutex is acquired before calling noTone() causing the mutex failed on noTone() therefore the object is never release. This will cause memory leak in the long run and eventually crash the mcu. Therefore fix #121 
Note: this Pr also add ToneHappyBirth to play the tune on the buzzer that some board is equipped with. This can help to quickly notice the issue in another tone() should it happen.
@ladyada
=> fix tone mutex

cores/rp2040/Tone.cpp, libraries/Servo/src/Servo.cpp, libraries/rp2040/examples/Siren/Siren.ino
The PIO programs that generate tone() and Servo() use the TX FIFO to
receive updates to the period/duty cycle.
The original code would push into the FIFO (potentially blocking the
app if the FIFO was full) and generate at least one cycle of every
value written into the control.  Basically, the output would
lag the changes by 1 cycle or more (which could be 20ms+ on Servo).
Fix this by clearing any old, ungrabbed values from the FIFO before
sending a new one to the program.  Instead of a FIFO, there is
effectively now just a control register and updates will be immediate.
Update the Siren.ino example with delays because now the tone() calls
will not block and run 10x+ faster.
=> Clear PIO FIFOs when updating Tone and Servos

cores/rp2040/SerialUART.cpp
Fixes a hang when reading from the Serial UART ports because before the
core would pause indefinitely for the next character.
Now, wait up to Serial.setTimeout() milliseconds and if it times out
return -1 to the app.
Fixes #210
=> Obey timeout value on SerialUART.read/.peek

libraries/SDFS/src/SDFS.h
The O_CREAT/etc. flags on the Pico are a full 32-bits in size, but the
core was generating a flag for SdFat using an 8-bit type, so all the
O_CREAT, O_TRUNC, O_APPEND, etc. flags got cut off.
Fix the flag size.
Fixes #214
=> Fix file creation on SD and SDFS

platform.txt
Fixes #236
Compiler warning flags were completely ignored/missed in platform.txt.
Add them, as normal, and include -Werror=return-type because GCC will
produce crashing apps when a function return value is missing.
=> Add warning flags to build, catch missing return

platform.txt
The Pico SDK has some magic with const pointers that generates lots of
"ignored qualifer" warnings on the more pedantic modes.  To clean the
normal builds up, disable this warning for now.  At some point a PR to
the PICO-SDK may be indicated.
````
In file included from /home/earle/Arduino/hardware/pico/rp2040//pico-sdk/src/rp2_common/hardware_timer/include/hardware/timer.h:11,
from /home/earle/Arduino/hardware/pico/rp2040//pico-sdk/src/common/pico_time/include/pico/time.h:11,
from /home/earle/Arduino/hardware/pico/rp2040//pico-sdk/src/common/pico_sync/include/pico/lock_core.h:11,
from /home/earle/Arduino/hardware/pico/rp2040//pico-sdk/src/common/pico_sync/include/pico/mutex.h:10,
from /home/earle/Arduino/hardware/pico/rp2040/cores/rp2040/CoreMutex.h:26,
from …
```
=> Disable ignored-qualifier warning in SDK

package/package_pico_index.template.json
Enable use of the included openocd binary with pico-debug
=> Update toolchain, add CMSIS-DAP to OpenOCD

cores/rp2040/wiring_analog.cpp
The PWM HW can only divide 125MHZ sysclk by 1...256.  That's only down to
about 500khz.  If the max count of the PWM (analogWriteScale) is too low
then the actual PWM period will be much less than desired (and PWM frequency
of course much higher).
For example, at analogWriteFreq(100); analogWriteScale(256); the true
PWM period would be 125M / 256 (pwmdiv) / 256 (scale) = ~2khz.
Conversely, at high frequencies and large scales it is impossible to achieve
the requested frequency and a much lower one would be generated.  For
example: freq(60K), scale(32768). PWM period = 125M / 1 (pwmdiv) / 32768 =
~4kHz.
Avoid this by adjusting the analogWrite scale in the core to either increase
the PWM count for low frequencies, or decrease it for high frequencies.
This is done behind the scenes and code …
=> Fix PWM frequency at low and high frequencies

cores/rp2040/RP2040USB.cpp, cores/rp2040/main.cpp, platform.txt
Use a libstdc++ compiled with -fno-exceptions to avoid including the
code needed to unwind C++ exceptions.
Saves 4K RAM and 6K flash.
=> Remove exception handling code, save RAM and FLASH

platform.txt
When a Python MSI/etc. is installed under Windows, it sets a global
PYTHONHOME and other variables.  Our shipped Python can end up using
these variables and attempt to load the wrong PYC files and fail
to run.
Avoid by using -I isolated mode in Python calls
Fixes #252
=> Avoid issues w/other installed Windows Pythons

platform.txt
As discussed in https://github.com/earlephilhower/pico-quick-toolchain/issues/4#issuecomment-882636739, without using `{}` in the OpenOCD program command, OpenOCD fails to find the to be uploaded ELF file. 
The PR fixes that escaping.
Additionally with replacing the shipped OpenOCD version with the one discussed in the issue to make OpenOCD able to connect to the board at all, the uploading now works. 
Working upload log:
```
C:\Users\Max\Desktop\Programming Stuff\arduino-1.8.13\hardware\pico\rp2040/system/openocd/bin/openocd -f interface/picoprobe.cfg -f target/rp2040.cfg -s C:\Users\Max\Desktop\Programming Stuff\arduino-1.8.13\hardware\pico\rp2040/system/openocd/share/openocd/scripts -c program {C:\Users\Max\AppData\Local\Temp\arduino_build_395124/Fade.ino.elf} verify reset exit 
Open …
```
=> Fix upload file path escaping for OpenOCD

libraries/Wire/Wire.cpp
Wire::requestFrom() returns the number of bytes read from the slave.  In
the case of error, the slave can end up returning a very large integer
for PICO_GENERIC_ERROR which would then be used as the # of bytes read
causing crashes and errors.
Running TalkingToMyself without connecting the I2C ports would show
this behavior.
Now, when PICO_GENERIC_ERROR is returned, set the read-back buffer len
to 0 explicitly.
=> Set available() to 0 when Wire.requestFrom fails

libraries/LittleFS/src/LittleFS.h, libraries/SDFS/src/SDFS.h
When LittleFS.begin() or SDFS.begin() is called after the filesystem is
already mounted, don't unmount/remount.  When an unmount happens, all old
Files become invalid (but the core doesn't know this), so you would end
up with random crashes in FS code.
Now, check for _mounted, and if so just return immediately from begin().
=> Make multiple begin calls noops SDFS/LittleFS

cores/rp2040/RP2040USB.cpp
Identify some spots that GCC's -fanalyzer noted might need nullptr
checks, and add them.
=> Minor paranoid nullptr checks in USB interface

platform.txt
Per #276, #277, #274 there seems to be an issue with interrupts and some
other low-level ARM operations when using the distributed libstdc++.
Use the default libstdc++ built with the toolchain, instead.
Fixes #277
Fixes #276
Fixes #274
=> Don't use no-c++-exceptions version of libstdc++

variants/adafruit_feather/pins_arduino.h
In troubleshooting issues using the STEMMA QT connector on my feather, I think I've discovered an issue with the board's variants file, specifically the WIRE lines below. The file seems to associate the i2c0 peripheral with the 2 and 3 pins, and doesn't seem to be attempting to assign any functional pins to i2c1.
https://github.com/earlephilhower/arduino-pico/blob/8451bc21ec4cca39f189a0493b2714749b272816/variants/adafruit_feather/pins_arduino.h#L29-L35
However looking at the Wires library, it doesn't seem like pins 2 and 3 are valid for i2c0 at all, but they are valid for the i2c1 peripheral.
https://github.com/earlephilhower/arduino-pico/blob/8451bc21ec4cca39f189a0493b2714749b272816/libraries/Wire/src/Wire.cpp#L50-L52
https://github.com/earlephilhower/arduino-pico/blob/8451bc21ec4cca39f18 …
=> Fix wire defines on feather

docs/platformio.rst
The correct option name is `board_build.<xyz>`, just as in the line below.
Just as in [the docs](https://docs.platformio.org/en/latest/boards/raspberrypi/pico.html).
=> Correct typo in PlatformIO docs

cores/rp2040/SerialUART.cpp, cores/rp2040/SerialUART.h
Because the hardware FIFO is quite small and doesn't report the actual number
of bytes available, implement a software FIFO that will pull all available
bytes out of the HW FIFO on any Serial call.  It's not as efficient or as
bulletproof as an IRQ based method, but it is simpler to implement and can
help with issues like #378
=> Add a poor-man's software FIFO for serial UART reads

libraries/SPI/SPI.cpp
Leave the SPI port initted after a transaction, and when a new one comes in
check if it is the same settings we're already running.  If so, do nothing.
If not, deinit and reinit.  In general the settings will be identical, so
this will speed things up massively.
Fixes #392
=> Speed up SPI by not reinitting if the paramters are the same as before

cores/rp2040/SerialUART.cpp, cores/rp2040/SerialUART.h
PR #379 was an ugly hack which works only if you poll the Serial port more
frequently than ~8 byte times.
This PR replaces the polling with an IRQ based lockless writer/reader queue
so that even if you only read every 32 byte times, the Serial1/2 port should
not lose data.  It also should use less CPU and allow for somewhat higher
throughput.
=> Use interrupts to capture Serial1/2 data, not polling

tools/platformio-build.py
Defines USBD_MAX_POWER_MA as a static 250mA, which is correct for all the boards supported in platform-raspberrypi (aka, RaspberryPi Pico and Nano RP2040 Connect) in accordance to [the generator code](https://github.com/earlephilhower/arduino-pico/blob/c80c08d32c07ff7704529f37f76bdb97030bfd8f/tools/makeboards.py#L157-L177).
Fixes previous build failure if attempting to use the latest core.
```
In file included from C:\Users\Max\.platformio\packages\framework-arduinopico/pico-sdk/lib/tinyusb/src/tusb.h:65,
from C:\Users\Max\.platformio\packages\framework-arduinopico\cores\rp2040\RP2040USB.cpp:28:
C:\Users\Max\.platformio\packages\framework-arduinopico\cores\rp2040\RP2040USB.cpp: In function 'const uint8_t* tud_descriptor_configuration_cb(uint8_t)': …
```
=> Fix PlatformIO build

variants/adafruit_qtpy/pins_arduino.h, variants/generic/common.h
This PR corrects the pin definitions for pins A0, A1, A2, and A3 on the Adafruit QT Py RP2040.
On this board, the four pins above are reversed compared to what's defined in the common pin configuration. The current way this PR is fixing this is to just use preprocessor `#define` in the board-specific `variants/adafruit_qtpy/pins_arduino.h` to override the `static const` declarations from `variants/generic/common.h` of those four pins. This method appears to work fine and compiles without warnings while keeping the general board variant style alive.
Another option for correcting this problem would be to copy all the pin definitions from `variants/generic/common.h` into the board's specific file with the required changes and just not include that `common.h` in it, but that way doesn't fit …
=> Fix some pin definitions for Adafruit QT Py RP2040

cores/rp2040/SerialPIO.cpp, cores/rp2040/SerialPIO.h, docs/piouart.rst
Defaults to 32 bytes, like the HW Serial ports, but can be set to
any desired value when instantiated.
=> Allow setting the SerialPIO FIFO depth in the constructor

cores/rp2040/SerialPIO.cpp, cores/rp2040/SerialUART.cpp, cores/rp2040/SerialUART.h, docs/serial.rst, keywords.txt
Allow setting the size of the receive buffer by the application using a
call to Serial1/2.setFIFOSize(xxx) before the begin() call.
=> Add setFIFOSize to UART Serial ports

libraries/Wire/src/Wire.h
=> Make Wire buffer default to 256 for MBED compatibility

libraries/Wire/src/Wire.cpp
The Pico HW seems to generate an interrupt on the end of every I2C
write cycle, even if the slave address wasn't actually targeted.
This would cause the onReceive method to be called with a 0-len
parameter for every write on the I2C bus.
Now, only call onReceive if there is 1 or more bytes of data available.
=> Only call Wire.onReceive if data is available

lib/platform_inc.txt
Fixes #427.  The libpico.a build already includes the HW interpolator
sources, but the include was missing from the Arduino path.
=> Add interpolater include path

tools/platformio-build.py
This fixes two things:
* the `ram_size` variable which is fixed at 256K. Previously PlatformIO's board definitions would have 264K there (+4K scratch x/y), which would generate a linker script with the content
```
MEMORY
{
FLASH(rx) : ORIGIN = 0x10000000, LENGTH = 1044480
RAM(rwx) : ORIGIN =  0x20000000, LENGTH = 264k
SCRATCH_X(rwx) : ORIGIN = 0x20040000, LENGTH = 4k
SCRATCH_Y(rwx) : ORIGIN = 0x20041000, LENGTH = 4k
}
```
i.e., the `RAM` section length would be off by 8K. 
* links **only** against `lib/libpico.a`, not `lib/libstdc++.a` by reworking the linkerflags (no `-L` flag to add to the search directory and `-lpico -lstdc++`, only link `libpico.a` by full path and source `libstdc++.a` from compiler). The `libstdc++.a` has weird errors which make the the system crash & burn when …
=> Fix libraries and RAM size in PlatformIO build

package/package_pico_index.template.json
Fixes #453, a crash caused by Newlib having ARM instructions in
the Thumb-only Cortex-M0+.
=> Update to 1.3.2-a toolchain, setjmp/longjmp fix

cores/rp2040/Arduino.h, cores/rp2040/wiring_analog.cpp
Most other boards and the MBED RP2040 support analogReadResolution which
just shifts read data around as needed, with a default of only 10b of
resolution.  The Pico ADC technically supports 12b, but only has about
8b of real data after noise, so you're not really losing anything in the
general case.
Fixes #460
=> Add support for analogReadResolution, default 10b

cores/rp2040/SerialPIO.cpp, cores/rp2040/SerialUART.cpp
Fixes #464 and other incompatibilities
Remove the timeout check from ::read and ::peek on the SerialUART/PIO
classes  (SerialUSB already ignores it).  See documentation
https://www.arduino.cc/reference/en/language/functions/communication/serial/settimeout/
and thanks to @jandrassy's explanation
https://github.com/earlephilhower/arduino-pico/issues/464#issuecomment-1031657044
=> Remove timeout for SerialUART/SerialPIO::read/peek

cores/rp2040/SerialPIO.cpp, cores/rp2040/SerialUART.cpp
Fixes #468
The FIFO limit was set to 1/2, or 16 bytes on POR and not set by the core,
so for low baud this could result in a LONG time without data moving from
hardware FIFO to the SW ring buffer and timeouts/etc.
Now use the API call which sets it to 1/8, or 4 bytes of data to speed up
the transfer 4x.
Also avoid using the divider in the IRQ routine because it is not clear
from the docs of the Pico SDK IRQ callback routine preserves divider
state or not.  If not, doing division in an IRQ could result in random
data corruption in the main app.
Add memory barriers to ensure the order of data into RAM is preserved
and that GCC doesn't reorder writes.
=> Decrease size of used FIFO in SerialUART

cores/rp2040/SerialPIO.cpp, cores/rp2040/SerialPIO.h, cores/rp2040/SerialUART.cpp, cores/rp2040/SerialUART.h, docs/serial.rst, keywords.txt
Fixes #472
Instead of using interrupts, explicitly call the IRQ handler dueing Serial
read/peek/available calls.
=> Add SerialUART::setPollingMode()

package/package_pico_index.template.json
GDB for non-Linux systems was built w/o expat which caused odd behavior
under Windows and other systems (i.e. breakpoints not working, etc.)
New toolchain manually builds cross-compiled libexpat and ensures it is
used, fixing the issue.
Windows OpenOCD binaries now come from manually built and tested copies
(using a real Windows system).
Fixes #478
Fixes #457
Fixes #456
and probably others...
=> Update GDB and OpenOCD to work together, finally

cores/rp2040/SerialPIO.cpp
Fixes #489
Only the PIO0 IRQ handler was ever installed due to a hardcoding bug.
Attach the IRQ handler to the PIO being started instead.
=> Fix SerialPIO receive interrupt on PIO1

libraries/PDM/src/PDM.h, libraries/PDM/src/rp2040/PDM.cpp, libraries/PDM/src/rp2040/pdm.pio, libraries/PDM/src/rp2040/pdm.pio.h
The PIO and state machine were hard wired as PIO 0 and SM 0, so this caused problems if they were not free. The approach used by the Servo library has been adopted to search for a free PIO and SM.
The DMA_IRQ_0 was grabbed exclusively, but this conflicts with the use with SPI DMA. The interrupt is now shared, but has been allocated the highest possible priority.
=> PDM library: Update PIO and interrupt use

tools/platformio-build.py
See https://github.com/platformio/platform-raspberrypi/issues/13#issuecomment-1066192398.
Originally from https://github.com/episource/platform-raspberrypi/blob/my-platform-pico/builder/frameworks/arduino-pico/arduino-pico.py#L104-L115 by @episource (thanks!). 
Fix looks very sensible to me for #477.
Effectively adds `lib_ignore = Adafruit TinyUSB Library` to the internal configuration during runtime (no file modifications to the `platformio.ini`) while respecting possible previously `lib_ignore` directives.
=> Auto-ignore Adafruit TinyUSB Library if not active

cores/rp2040/SerialUART.cpp, cores/rp2040/SerialUART.h
The UART FIFO will generate an IRQ to transfer data into the SerialUART
FIFOs either every 4 received bytes, or every 4 idle byte times.  This
causes the ::available count to report "0" until either of those two
cases happen, causing a potentially delay in data becoming available to
the app.
Change the code to pull data from the HW FIFO on a read/available/peek.
Use a non-blocking mutex and IRQ disabling to safely empty the FIFO from
user space.  The mutex added to the IRQ is non-blocking and will be
a single CAS the vast majority of the time, so it should not impact the
Serial performance.
Fixes #464 and others where `setPollingMode()` was needed as a workaround.
=> Avoid "chunkiness" of UART FIFO availability

tools/uf2conv.py
udisks >= 2.9.0 dropped the period at the end.  Adjust regex to look a period or newline.
Fixes: #515
Upstream reference: https://github.com/storaged-project/udisks/commit/6842123525966ad5fd5dfa5eccef43c3ea985c21
=> udisks v2.9.0 dropped the trailing period for "udisksctl mount".

cores/rp2040/SerialPIO.cpp
Adjust the 1/2 bit time to match the number of extra cycles in the actual
PIO loop.
Shift out the entire start bit, which results in sampling the data at the
midpoint and not the starting time of a bit.
Tested at 300bps all the way to 2,000,000bps using a loopback connection.
Fies #360
=> Fix SerialPIO sampling, avoid reading random garbage

cores/rp2040/SoftwareSerial.h, docs/piouart.rst
I receive mails weekly asking how to use `SoftwareSerial` on this core.
Avoid the issue by including a simple wrapper class around `SerialPIO`
which gives the proper class name and constructor parameters.
Note that inverted mode is not supported.
=> Add SoftwareSerial wrapper around SerialPIO

libraries/FreeRTOS/src/FreeRTOSConfig.h, libraries/FreeRTOS/src/port.c, libraries/FreeRTOS/src/variantHooks.cpp
Use low power WFE when idle.
Set PORT.C to built `-O0` always because it seems to occasinally end
up with interrupts disabled in task code, causing the SYSTICK never to
fire and killing task switching.
No need for dynamic exceptions.  We don't move the execbase.
=> Additional FreeRTOS adjustments

libraries/FreeRTOS/src/port.c
To remove compiler warning the valid core macro was modified to only check
that the core passed in was < # of total cores.  Unfortunately there are
parts of the FreeRTOS code where the passed in core # is -1.  The upstream
catches this and returns FALSE, but my hacked version returned TRUE.  This
caused interesting memory corruption errors and crashes when the
current task block[-1] was updated.
Undo the change and fix the 1 spot where a warning happens instead.
Undo the forced compiler -O0 for port.c, it was only masking the fault.
=> Fix memory corruption introducted in FreeRTOS port

variants/adafruit_qtpy/pins_arduino.h
As discussed in [issue 504](https://github.com/earlephilhower/arduino-pico/issues/504)
=> correct Serial1 and Serial2 pinout definitions added

libraries/Wire/src/Wire.cpp
Fixes #585
On an I2C bus restart, call the onReceive callback and clear the buffer.
Thanks to @DWiskow for the debug and patch!
=> Fix Wire I2C restart handling

cores/rp2040/wiring_private.cpp
Fixed #601
Allows apps to provide a callback parameter in the `attachInterrupt` call
to be passed back to the function when the interrupt happens.
=> Add attachInterruptParam

libraries/Wire/src/Wire.cpp
Avoids returning 2^32 bytes in the case of a requestFrom read fails
due to timeout.
=> Fix Wire::available() when ::requestFrom fails

variants/wiznet_wizfi360_evb_pico/pins_arduino.h
Slight difference to generic RP2040
PIN_SERIAL2_TX + PIN_SERIAL2_RX are
switched with PIN_WIRE0_SDA + PIN_WIRE0_SCL
=> Fix WizFi360-EVB-Pico pins_arduino.h

package/package_pico_index.template.json
Free up 4K of RAM and 6K of flash when no exceptions are enables (default).
The original toolchain was including exception code in libstdc++ by default.
Reduce installation by ~50MB and download by ~25M by removing unused LTO
gcc support.
=> Reduce flash, RAM use, reduce download/install

tools/platformio-build.py
The Arduino IDE / `platform.txt` builds this core by using a `-iprefix <framework path>` directive followed by the file in https://github.com/earlephilhower/arduino-pico/blob/master/lib/platform_inc.txt.
This however causes problems in PlatformIO because for the Intellisense of IDEs, since only what is in `env["CPPPATH"]` is exported as to be searched include path for headers is exported by PlatformIO. It's not smart enough to scan the compiler invocations for `iprefix` etc lines and reconstruct the paths from that for the IDE.
This restructures the build script to read the contents of the `platform_inc.txt` file, reconstruct the full path and then add them to `env["CPPPATH"]`. This fixes IntelliSense issues on Mac and Linux. Most interestingly, this did not affect Windows intellisense. …
=> Fix IDE include paths / Intellisense

tools/platformio-build.py
Very simple addition: Build with `-Os` by default Other builder scripts [do the same](https://github.com/stm32duino/Arduino_Core_STM32/blob/main/tools/platformio/platformio-build.py#L229-L230).
This is as always overridable with e.g.
```ini
build_unflags = -Os
build_flags = -O2
```
Needed for multicore and / or race-free malloc/free to work, see https://github.com/maxgerhardt/platform-raspberrypi/issues/7#issuecomment-1152519265
=> Activate default -Os optimization

docs/platformio.rst
* Fixes that the link is properly displayed (see https://arduino-pico.readthedocs.io/en/latest/platformio.html#selecting-a-different-core-version)
* Remove warning regarding JLink Filesystem Upload (implemented in https://github.com/maxgerhardt/platform-raspberrypi/commit/d24609b89e26da75a5a7fe01df2b98818716611f)
* Remove unfinished, dangling sentence
(Docs should be rebuilt thereafter.)
=> Minor PIO Docs Fixup

cores/rp2040/lock.c
There was a race condition in making mutexes that were only init in
an __attribute((constructor)) code block.  For example, a global
object might do a `malloc` in its constructor which would depend on
the malloc mutex...which may not yet have been initted.
Make them initted in the .data section, instead, which is guaranteed
good before any global constructors are called.
=> Make mutexes init in DATA, not ((constructor))

tools/platformio-build.py
Closes #630.
As written in https://github.com/earlephilhower/arduino-pico/issues/630#issuecomment-1159775571, the TinyUSB library only works with PlatformIO during runtime if its object files are linked individually in the firmware instead of archiving them into a `.a` file and linking that.
So that users don't have to write
```ini
lib_archive = no
```
into their `platformio.ini` ([docs](https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-archive)) and to make the docs valid (they say only `build_flags = -DUSE_TINYUSB` is needed), a small addition to the builder script is made which adds this option automatically.
So this is equivalent to https://github.com/adafruit/Adafruit_TinyUSB_Arduino/pull/116 on the framework builder script side.
It is still interesting …
=> Make TinyUSB linking work automatically with PIO

docs/usb.rst
Closes #648 by documentating said findings.
PlatformIO specific instructions were tested locally and found to work.
=> Add notes on TinyUSB documentation and quirks

cores/rp2040/SerialUSB.cpp
Before always returned 0 on a ::write.  Now properly return the count
of bytes that were sent to the USB port.
Thanks to Terry Haas for the report.
=> Return # of bytes written by SerialUSB::write

tools/platformio-build.py
Fixes the issue discussed in https://github.com/earlephilhower/arduino-pico/issues/66#issuecomment-1191300424.  The issue description and fix are basically the same as in https://github.com/espressif/arduino-esp32/pull/6809. 
Test case
```ini
[env:rpipicow]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board = rpipicow
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
```
Before fix: initVariant is an empty function, returns immediately (the `_weak` default)
```
> C:\Users\Max\.platformio\packages\toolchain-rp2040-earlephilhower\bin\arm-none-eabi-objdump.exe -d .\.pio\build\rpipicow\firmware.elf  | grep -A5 initVariant
100008a4 <initVariant>:
100008a4:       4770            bx      lr
```
After fix: initVariant for the RPiPico W …
=> Fix PlatformIO linking for variant-specific overrides

docs/bearssl-client-secure-class.rst, docs/wifintp.rst, libraries/WiFi/keywords.txt, libraries/WiFi/src/WiFiClientSecure.h, libraries/WiFi/src/WiFiClientSecureBearSSL.cpp, libraries/WiFi/src/WiFiClientSecureBearSSL.h, libraries/WiFi/src/WiFiNTP.h, libraries/WiFi/src/include/ClientContext.h
Simple sketches should work without modification, but some modes (listed
in the docs) are not possible to support on the Pico W with BearSSL.
Fixes #691
=> Add basic ESP32 WiFiClientSecure support

docs/wifintp.rst, libraries/WiFi/examples/BearSSL_CertStore/BearSSL_CertStore.ino, libraries/WiFi/examples/BearSSL_ServerClientCert/BearSSL_ServerClientCert.ino, libraries/WiFi/examples/BearSSL_Sessions/BearSSL_Sessions.ino, libraries/WiFi/examples/BearSSL_Validation/BearSSL_Validation.ino, libraries/WiFi/src/WiFiNTP.h
Allows printing "."s or flashing an LED while NTP is waiting for sync.
=> Add NTP waitSet callback

platform.txt
Adds compiler flags to correctly build Cortex-M0/M0+ code variants for
libraries inside of the ARM CMSIS codebase.
This was tested with the Arduino_CMSIS-DSP 5.7.0 library,
located at https://github.com/arduino-libraries/Arduino_CMSIS-DSP
=> platform.txt: Add compiler flags for ARM CMSIS

libraries/I2S/src/I2S.cpp
BCLK was running at 50% of expected speed.
Fixes #714
=> Fix I2S timing

cores/rp2040/SerialUART.cpp
Fixes #735 .  Thanks to @ Haggarman for the find and fix.
=> Fix UART wrong ::available() during wraparound

libraries/WiFi/src/include/UdpContext.h
Attempting to send UDP packets to IPv6 addresses resulted in `ERR_VAL` (-6) due to the `IP_ADDR_PCB_VERSION_MATCH(pcb, dst_ip)` check failing because `local_ip` defaults to the IPv4 address `0.0.0.0`
=> Fix sending of IPv6 UDP packets

libraries/FreeRTOS/src/FreeRTOSConfig.h
PR to fix issue #751 FreeRTOS : configTIMER_TASK_STACK_DEPTH is too low which is causing system hang
Original value of configTIMER_TASK_STACK_DEPTH is 80 which is too low.
Proposal is to increase to 1024.
=> Increase FreeRTOS timer task stack to 1024

docs/fs.rst, docs/ota.rst, libraries/SD/src/SD.h, libraries/SDFS/src/SDFS.h
=> Allow selecting SPI port for SD/SDFS filesystem

cores/rp2040/RP2040Support.h
rp2040.reboot() would set a reboot timer for 100ms in the future, but then
return to user code and doing stuff until the timer expired.  Now wait
until the WDT fire.
=> Don't return from reboot

cores/rp2040/sdkoverride/cyw43_arch_threadsafe_background.c, libraries/Updater/src/Updater.cpp, libraries/WiFi/src/WiFiClass.cpp, libraries/WiFi/src/WiFiMulti.cpp, libraries/lwIP_CYW43/src/utility/CYW43shim.cpp
There may be an issue in the CYW43 driver that causes a link to never be
reported as going down once it has connected, when it was disassociated or
when the wlan shuts off unexpectedly.
Work around it by clearing the internal link active in a TCP callback for
the CYW43 driver.
Reports disconnection properly now, as well as reconnection.
Fixes #762
=> Report ::connected() as false when WiFi link drops

libraries/WiFi/src/WiFiMulti.cpp
If the WiFi network is already up, don't run the scan and connection
algorithm in WiFiMulti.
=> Avoid rescanning/connecting on WiFiMulti.run

libraries/ArduinoOTA/src/ArduinoOTA.cpp, libraries/WiFi/src/BearSSLHelpers.cpp
Give a meaningful error when OTA is attempted against a chip which does
not have a filesystem configured.
=> Report "no filesystem" on OTA uploads w/o a FS

libraries/Updater/src/Updater.cpp, platform.txt
Force the builder to include the path where we build the signing header.
Undo a breaking bug in the Updater class (TBD fix in ESP8266)
Fixes #783
=> Fix OTA signing

libraries/ArduinoOTA/src/ArduinoOTA.cpp, libraries/Updater/src/Updater.cpp
OTA text error messages were getting lost because they were sent in
multiple UDP packets, one per print(). Now collect the full error and
report in a single print, allowing text messages to appear in ESPOTA.
=> Ensure OTA errors are sent in single UDP packet

README.md
This PR adds a link to my Pico W/Home Assistant integration starter project to the tutorials listing. Thanks to your efforts, it's so easy to get a Pico W into the IoT mix. This project pulls together everything I've learned to make that possible in the last couple months.
If you think it might be of interest to visitors, feel free to merge!
=> Add Home Assistant starter to tutorials listing

libraries/WiFi/src/WiFiClass.h
This PR reverses the printing order of the MAC Address octets in methods `softAPmacAddress` and `macAddress` of the WiFi class.
=> Fix WiFi MAC Address string output

cores/rp2040/SerialUSB.cpp
Fixes #816
If a byte is available, return it even if the USB stack reports
disconnected.
=> Avoid potential lockup w/Serial.read unconnected

libraries/WebServer/src/HTTPServer.cpp
Avoid creating Strings when sending out results.
=> Clean up WebServer send() methods

libraries/WiFi/src/WiFiUdp.cpp, libraries/WiFi/src/WiFiUdp.h
Fixes #747 while remaining ESP8266 compatible
=> Add upsteam multicast compatibility APIs

platform.txt
Should speed builds up slightly, depending on the OS and virus scanning.
=> Use pipes between GCC stages

cores/rp2040/SerialPIO.cpp, cores/rp2040/SerialPIO.h, variants/arduino_nano_connect/pins_arduino.h
Fix [**Add Serial3 for Arduino Nano Connect RP2040** #807](https://github.com/earlephilhower/arduino-pico/pull/807)
Tested OK with this core using [**FirmwareUpdater**](https://github.com/khoih-prog/WiFiNINA_Generic/tree/master/examples/Tools/FirmwareUpdater) from [**WiFiNINA_Generic** library](https://github.com/khoih-prog/WiFiNINA_Generic)
=> Add Serial3 for Arduino Nano Connect RP2040. Fix #807

cores/rp2040/SerialUSB.cpp
Add calls to `tud_task` to pump the USB interface in the SerialUSB methods.
See #832 for more info.
=> Increase SerialUSB speed

cores/rp2040/RP2040Support.h, docs/rp2040.rst
Addresses and resolves https://github.com/earlephilhower/arduino-pico/issues/861 by adding two function helpers for basic hardware watchdog access and one function for entering low-power sleep (WFE) mode.
cc @earlephilhower
=> Add WDT and sleep functions to RP2040 Helper

docs/httpclient.rst
There was a minor copy-paste error in the HTTPS example in the docs.
=> Fix typo in HttpClient HTTPS example

libraries/lwIP_Ethernet/src/LwipIntfDev.h
When moving between different modes or even WiFi.begin/ends, any setting of the IPs will fail because the internal flag _started was not cleared. Clear _started on a ::end call.
Fixes #884
=> Clear LWIP started flag on LWIPIntfDev::end

cores/rp2040/wiring_analog.cpp
PR for issue #917.
First commit fixes the overflow and wrap value. 
Second commit extends the frequency range to 10 MHz. For this to work also at low system clocks (down to 50 MHz, since that's what is available in the IDE menu), I had to decrease the lower bounds of the range and resolution. Also changes the adjustment loops to allow clkdiv values down to 1.0, to make it possible to manually set
well-chosen frequency and range values to avoid using the prescaler.
I've tested at system clocks 50MHz, 133MHz, 150MHz and with different frequencies. From what I've seen it always works, however the frequency obtained can be off by several percent when ending up with small and non-integer prescaler values. This happens when requesting a high frequency and a large range.
=> Pr analog write

cores/rp2040/_freertos.cpp
There's a memory leak around the corner: creating the mutex means that we allocate memory for it, but if we cannot find any free slot in the FMMap array, we're simply returning a nullptr without ever freeing the previously allocated memory.
Instead of allocating it out of the free-slot check, do it inside. While at it, also check if the mutex creation succeeded before assigning it to a FMMap slot.
=> cores/rp2040: _freertos.cpp: Avoid memory leak and unnecessary allocation

cores/rp2040/sdkoverride/cyw43_arch_threadsafe_background.c
=> Properly disable Ethernet IRQ, don't drop packets

cores/rp2040/main.cpp
Using PIO_FRAMEWORK_ARDUINO_NO_USB build flag would cause internal rp2040 fifo not being initialized correct.
=> Using NO_USB definition would make rp2040 fifo uninitialized

libraries/EEPROM/src/EEPROM.cpp
The memcpy to unallocated memory in EEPROMClass::begin() was done in two cases: 
1) The 'size' parameter was not multiple of 256.
2) The begin() was called two times and the 2nd call 'size' was greater than 1st time 'size'. (e.g. 1st size=256, 2nd size=512)
This simple change fixes both of them.
=> Fix memcpy to unallocated memory in EEPROM.cpp

libraries/WiFi/src/include/ClientContext.h
Instead of sending a single packet per byte, send out larger chunks to TCP/IP while doing a ::write(Stream).
Fixes #999
=> Speed up ClientContext::write(Stream) by chunking

tools/pluggable_discovery.py
When receiving a `QUIT` message, the main thread was trying to tell    the scanner thread to quit - however, what it was actually doing was creating a local variable that shadowed the global flag used by the scanner thread. Fix that by ensuring that the main thread uses the global variable instead.
Fixes #1028
=> pluggable_discovery: Allow the scanner thread to quit

cores/rp2040/FS.cpp
Previously, `File::readString` used a C-style string as an intermediate buffer via the `String` += operator. This treats a NUL byte as a terminator, making this function work incorrectly if the File contains binary data.
This commit switches the function to use `String::concat`, which doesn't treat NUL bytes any differently (and is a bit faster, because it doesn't need to use `strlen`).
=> Fix File::readString to work with binary data

cores/rp2040/SerialUART.cpp
Fixes #1021
The UART hardware will push characters into the receive FIFO even if there are parity, framing, or other errors.  These are invalid and shouldn't be returned to the application, so drop them if errors detected.
This will also avoid the glitch-induced initial garbage character.
=> Throw away UART bytes with errors in reception

libraries/WiFi/src/WiFiClass.h
Fixes #1031, or at least covers the case of slower associations.
=> Increase WiFi.begin() default timeout to 15s

libraries/WiFi/src/include/ClientContext.h
Other parts of the core use temp 256 byte chunks to transmit/move/operate on data, so do the same here.  Will increase effective WebServer sendFile speeds.
=> Increase ClientContext write(Stream) to 256b chunk

libraries/I2S/src/AudioRingBuffer.cpp
Fixes #963
The available space calculation didn't account for the fact that one of the buffers was currently being output, causing ::available() to be too large and ::write() to block in that case.
=> Fix I2s::available() to skip currently playing

libraries/WiFi/keywords.txt, libraries/WiFi/src/WiFiClass.cpp, libraries/WiFi/src/WiFiClass.h
I was not very happy with pico-w WiFi stability, with huge WiFi traffic around the connection from my AP to pico-w was really unstable. 
After some testing I discovered, that something (probably inside cyw43-driver) is periodically delaying wifi operations.
The ping response suffered from periodical delay which went up to 10 seconds in some cases (see the screenshot of ping from my server to pico-w):
After some research I found that the delay is caused by the power saving behavior of the WiFi chip.
There are existing two functions inside the arduino-pico WiFiClass: lowPowerMode() and noLowPowerMode(). 
Both of them are unfortunately using power saving modes (CYW43_AGGRESSIVE_PM and CYW43_DEFAULT_PM).
After reading this: https://forums.raspberrypi.com/viewtopic.php?t=340050#p2037055
and …
=> Modified LowPowerMode functions in WiFiClass.cpp/.h for better connection stability

tests/common.sh
Avoids errors shown in logs for certain builds.
=> Fix CI errors when more than one *.a in cache dir

package/package_pico_index.template.json
Newer OpenOCD: sysfsgpio, bcm2835gpio, cmsis-dap-v2 support
Raspberry Pi packaging fixes
=> Update to 1.5.0-a toolchain

libraries/I2S/keywords.txt, libraries/I2S/src/AudioRingBuffer.cpp, libraries/I2S/src/AudioRingBuffer.h, libraries/I2S/src/I2S.cpp
The ring buffer worked but had issues with IRQs and the available() procesing.  Because it was a pain to debug, move to a linked list setup where there are filled and empty buffers to work from, simplifying the underlying logic.
Allow I2S::available() to return free writing space in OUTPUT mode to make it saner.
=> Make the AudioRingBuffer list-based

cores/rp2040/wiring_analog.cpp
Saves 28 bytes by using a bitmask and smaller ADC settings globals, see #1072
~1% performance impact so negligible.
=> Reduce ADC memory footprint slightly

cores/rp2040/Arduino.h, cores/rp2040/wiring_analog.cpp
Fixes `analogReadTemp()` by automatically using the correct ADC resolution and optionally also a different reference voltage.
This does not introduce any breaking changes, everything will work like it did (except, if you wanted a wrong temperature reading on purpose) as the default Vref is 3.3 V.
Users can supply their own custom voltage directly in the `analogReadTemp(float vref)` call to make this change as simple as possible.
Tested it on my setup, works like expected with 3.0 V reference and 12-bit ADC.
=> Universal analogReadTemp()

cores/rp2040/Arduino.h
Per https://github.com/earlephilhower/arduino-pico/issues/1067:
#define digitalWriteFast(pin,val) (val ? gpio_set_mask(1 << pin) : gpio_clr_mask(1 << pin))
#define digitalReadFast(pin) gpio_get(pin)
gives an 8.76 MHz ring (at 250 MHz clock);
#define digitalWriteFast(pin,val) (val ? sio_hw->gpio_set = (1 << pin) : sio_hw->gpio_clr = (1 << pin))
#define digitalReadFast(pin) ((1 << pin) & sio_hw->gpio_in)
gives a12.9 MHz ring.
=> digitalRead/WriteFast to sio_hw->gpio

libraries/FreeRTOS/examples/Multicore-FreeRTOS/Multicore-FreeRTOS.ino, libraries/SingleFileDrive/examples/DataLoggerUSB/DataLoggerUSB.ino, libraries/WiFi/examples/BearSSL_Sessions/BearSSL_Sessions.ino, libraries/WiFi/examples/BearSSL_Validation/BearSSL_Validation.ino, libraries/WiFi/examples/ScanNetworks/ScanNetworks.ino, libraries/rp2040/examples/GetCycleCount/GetCycleCount.ino
Let GCC check the format string to Print::printf().  Will catch when sketches use incorrect parameters to `Serial::printf()`.
=> Warn when `Serial.printf()` format is wrong

cores/rp2040/wiring_analog.cpp
`adc_read()` resolution is always 12 bits. Doesn't change with `analogReadResolution()`.
This is basically a partial reversal #1075.
=> Fix temperature reading resolution

libraries/SingleFileDrive/src/SingleFileDrive.cpp, libraries/SingleFileDrive/src/SingleFileDrive.h, libraries/WebServer/examples/AdvancedWebServer/AdvancedWebServer.ino, libraries/WiFi/src/dhcpserver/dhcpserver.c
Only 4K total stack, so allocating 400 bytes for a local C string or 600 bytes for a DHCP response is dangerous.  Use static allocations instead on the heap.
=> Reduce stack usage of several components

libraries/I2S/src/pio_i2s.pio, libraries/I2S/src/pio_i2s.pio.h
The word select bit (WS) convention is inverted between I2S (down for left) and LSBJ (down for right). This inverts the behavior of this bit for the LSBJ format.
I am sorry about the whitespaces changes…
=> Set Right and Left correctly for lsbj format

cores/rp2040/Arduino.h, libraries/I2S/src/pio_i2s.pio.h
Now that we have a default parameter, need to only allow it in C++ since default values are not part of C spec.  Should not affect any users since only legacy code is in C.
=> Move analogReadTemp() to C++-only

docs/install.rst
Provide instructions for users to override filesystem access restrictions imposed by Flatpak on some installations of the Arduino IDE
=> Add additional instructions for Linux Flatpak users

tools/uf2conv.py
Fixes #1140
````
Converting to uf2, output size: 134144, start address: 0x2000
ERROR: Unable to execute powershell or wmic commands, can't continue.
ERROR: Please make sure either PowerShell or WMIC is installed and in
your %PATH%.
````
=> Print useful uf2conv error if executable not found

boards.txt, cores/rp2040/RP2040USB.cpp, platform.txt, tools/makeboards.py
The USB VID was always being set to the Raspberry Pi foundation code, causing other brand boards to show up incorrectly.
Remove redundant values from the boards.txt and define a consistent USB VID/PID and use it in the setup code.
See #1129 for more info
=> Fix USB VID/PID setting, rationalize boards.txt

libraries/SPI/src/SPI.cpp
The SPI `transfer16()` function returned wrongly oriented bytes. Replaced `reverseByte()` with `reverse16Bit()`.
=> Fixed issue  #1146

cores/rp2040/SerialUART.cpp
Fixes #1153
Set up the GPIO redirects before the UART is pulled from reset to avoid a possible bad byte at `Serial1/2.begin()`.
=> Avoid initial glitch on Serial1/2 when RX high

libraries/PDM/src/PDM.h, libraries/PDM/src/rp2040/PDM.cpp
pulled in the changes from arduinocore-mdbed, leaving the dynamics of pio/sm and dma_channel assignment in arduino-pico untouched. Due to this, additional clean-up has to be done in `PDM::end` compared to arduino-mbed.  Begin and end can now be called as often as desired, but works almost ( fail in one of about every 50-100 end-begin cycles ). Error Scenario now is either all data returned by `PDM::read` is -128's or toally rubbish looking like a missing byte swap for the shorts or a mismatch in the byte index to build the shorts. For now, observed only when forcing a movement from one sm to another of the same pio by claiming the former sm. Forcing load of pdm_pio_program to new sm by resetting `_offset` in PIOProgram::prepare after `pio_remove_program` in  `PDM::end` doesn't help. Where …
=> pdm re-port(#1156)

libraries/AudioBufferManager/src/AudioBufferManager.cpp
Fixes #1162
Disable DMA interrupts while we're tearing down an AudioBufferManager and explicitly clear any potential leftover IRQs to avoid hangs.
=> Avoid race condition in I2S/PWMAudio delete

libraries/SD/src/SD.h
O_RDWR != O_READ|O_WRITE.  Posix is weird.  Thanks @mcspr
=> Fix SD.H FILE_WRITE mapping

cores/rp2040/SerialUSB.cpp
USB changes caused FreeRTOS to not be able to swap tasks when the Serial port was connected.  Clear the "stop PendSV" flag after checking for reset signal.
=> Unbreak FreeRTOS

cores/rp2040/_freertos.cpp, cores/rp2040/_freertos.h, cores/rp2040/lock.cpp
The stdin/stdout FILEs have an internal mutex which needs to be initted to a FreeRTOS one, or any sketch with ::printf will hang.  Automatically create and acquire/release the shadowed mutex.
Requires new build of pico-quick-toolchain to function properly.  Tested on preliminary local build.
=> Allow FreeRTOS to ::printf

lib/memmap_default.ld
Use GNU LD MAX() to ensure the uninitialized RAM portions are after the OTA region.  For most apps this already happens, so there will be no overhead added.
=> Reduce unintialized_ram overhead to 0 in most cases

libraries/SPI/src/SPI.cpp
For #1201. See issue thread for more info.
This PR simply removes line of code that was doing the extra byte flipping.
=> Remove extra SPI byte flip

docs/adc.rst
=> Fix spelling mistake

lib/picoprobe_cmsis_dap.tcl
Still need it on the command line in platform.txt for upload/etc., but make the debug script in lib/picoprobe_cmsis_dap.tcl include the adapter speed setting.
=> Always apply 5M speed to CMSIS_DAP TCL script

variants/rpipicow/picow_digital.cpp, variants/rpipicow/pins_arduino.h
Many examples require that LED_BUILTIN be defined as a constant, so we can't use a ternary operator to swap between Pico and PicoW LED pins.
Instead, do the check in the digitalWrite/digitalRead/pinMode calls to cover most of the uses.
=> Move PicoW auto-reassignment of LED pin to code

cores/rp2040/RP2040USB.cpp
Return the pre-existing USB_PRODUCT/MANUFACTURER to the USB host in the ID stage, allowing for reports like:
[1412958.589070] usb 1-6.3.4.1: New USB device found, idVendor=2e8a, idProduct=f00a, bcdDevice= 1.00
[1412958.589076] usb 1-6.3.4.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[1412958.589079] usb 1-6.3.4.1: Product: Pico W
[1412958.589080] usb 1-6.3.4.1: Manufacturer: Raspberry Pi
[1412958.589081] usb 1-6.3.4.1: SerialNumber: E6614C775B6C7F31
or
[1413190.272233] usb 1-6.3.4.1: New USB device found, idVendor=2e8a, idProduct=1037, bcdDevice= 1.00
[1413190.272239] usb 1-6.3.4.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[1413190.272242] usb 1-6.3.4.1: Product: HunterCat NFC RP2040
[1413190.272243] usb 1-6.3.4.1: Manufacturer: ElectronicCats …
=> Return custom USB product and manufacturer

cores/rp2040/RP2040USB.cpp, libraries/Keyboard/examples/KeyboardPassword/KeyboardPassword.ino, libraries/Keyboard/src/Keyboard.cpp, libraries/Keyboard/src/Keyboard.h, libraries/KeyboardBT/examples/BTKeyboardPassword/BTKeyboardPassword.ino, libraries/KeyboardBT/src/KeyboardBT.cpp
BLE seems to require some kind of characteristic callback that is not yeet implemented here.  USB and BT tested and examples updated.
=> Add Keyboard LED callback for USB and BT (not BLE)

variants/adafruit_feather_scorpio/pins_arduino.h
Referencing #1216 and basing it off these pinouts (https://learn.adafruit.com/introducing-feather-rp2040-scorpio/pinouts) as this board uses Wire1 for the "main" broken-out I2C pins, the stemma port included. Can confirm that's the case for mounted featherwings that use this board's I2C.
Basing Wire0's pins from the base RP2040 pindefs, which match with this board's as well. (Base RP2040 pinout: https://learn.adafruit.com/adafruit-feather-rp2040-pico/pinouts)
Sidenote: This also applies to the SPI pins (should be on SPI1, but otherwise SCK, MOSI, and MISO pins check out) but can't fully confirm the SS pin and it's originally commented as "Not pinned out."
=> Reassign Feather Scorpio I2C pins to correct buses

libraries/lwIP_CYW43/src/utility/CYW43shim.cpp
SDK 1.5 changed the behavior of the underlying CYW43 blob, and it seems to block MDNS multicast by default.  Manually add back the Ethernet MACs used for MDNS multicast in IPV4 and IPV6.
Fixes #1267
=> Manually add MDNS multicast Ethernet MACs to CYW43

variants/adafruit_feather_dvi/pins_arduino.h
Fix SPI and Wire so even tho we are using the 'second' peripherals, they are usable as `SPI` and `Wire` :)
=> Feather DVI peripheral fix

cores/rp2040/RP2040USB.cpp, libraries/Keyboard/examples/KeyboardPassword/KeyboardPassword.ino, libraries/Keyboard/src/Keyboard.cpp, libraries/Keyboard/src/Keyboard.h, libraries/KeyboardBLE/src/KeyboardBLE.cpp, libraries/KeyboardBLE/src/KeyboardBLE.h, libraries/KeyboardBT/src/KeyboardBT.cpp, libraries/KeyboardBT/src/KeyboardBT.h
Allow sending thigns like KEY_MUTE or KEY_SCAN_NEXT from the USB and Bluetooth Classic keyboard libraries.
BLE requires some add'l magic, not yet discovered.
=> Add HID consumer (aka media) keys for USB, BT

cores/rp2040/Arduino.h, cores/rp2040/CoreMutex.h
See #1311 for more info.  __isFreeRTOS is C++ linkage and only used in the core proper (all C++).
=> Clean up CoreMutex and __isFreeRTOS definition

variants/adafruit_feather_usb_host/pins_arduino.h
Change “N” to “M” and add “HOST” in the USB pins at @hathach’s request. Only two pins are actually affected; diff appears large to maintain the pleasant aligned-columns format. Boards are still in production pipeline and this shouldn’t affect any customers.
=> Rename USB HOST pins

cores/rp2040/_needsbt.h, libraries/BTstackLib/src/BTstackLib.h, libraries/HID_Bluetooth/src/PicoBluetoothBLEHID.h, libraries/HID_Bluetooth/src/PicoBluetoothHID.h, libraries/SerialBT/src/SerialBT.h
Fixes #1370
Adds a simple helper assertion to tell the user how to enable BT if it's not enabled, instead of some odd compilation warnings about undefined functions.
=> Clear compile errors if BT needed but not on

cores/rp2040/CoreMutex.cpp, libraries/FreeRTOS/src/variantHooks.cpp
Fixes #1402
The global USB mutex is auto-shadowed with a FreeRTOS semaphore while in FreeRTOS mode.  Unfortunately, while the core was using the proper FreeRTOS semaphore to lock access to the USB port, the actual FreeRTOS USB task was using the naked Pico SDK mutex, leading to cases where it could acquire the mutex even though some other FreeRTOS task actually owned the shadowed mutex.
Properly lock the shadowed Semaphore, not mutex_t, in the FreeRTOS USB periodic task.
=> Fix USB crashes in FreeRTOS

cores/rp2040/RP2040USB.cpp
Fixes #1410
The USB Keyboard now has 2 reports (keyboard + consumer control), so when both Keyboard and Mouse libraries are included, the Mouse must be report 3, not 2.
Update the Mouse and Joystick report IDs appropriately.
=> Fix USB Mouse/Joystick HID report ID

cores/rp2040/main.cpp, libraries/FreeRTOS/keywords.txt, libraries/FreeRTOS/src/FreeRTOSConfig.h, libraries/FreeRTOS/src/tasks.c
Update to head of upstream FreeRTOS/SMP branch.  Very minor changes.
Remove the custom getreent implementation, use the one that was defined in the upstream FreeRTOS/smp branch (callback related vs. static vars).
=> Merge latest FreeRTOS/SMP upstream branch

libraries/BTstackLib/src/BTstackLib.cpp, libraries/BTstackLib/src/BTstackLib.h
Added a simple function overload to BTstackManager::setup()  to allow a name for the BT instance to be passed.
=> Added function overload to pass name to setup().

libraries/AudioBufferManager/src/AudioBufferManager.cpp
If `dma_claim_unused_channel(true)` panics when none are available, then why have the check if it returned -1? 
I think you might mean `dma_claim_unused_channel(false)`, so that begin() can just return false.
Warning:
I'm sorry, but I haven't tested it. And to be honest, I'm not even completely sure what exactly these functions do. Please review carefully. I hope this is still useful.
=> make dma_claim_unused_channel() not panic in AudioBufferManager::begin()

cores/rp2040/SerialUSB.cpp
The serial port reset logic was calling `sleep_ms()` which ended up doing a task switch...while the other core was frozen and everything was supposed to be locked.
Use `busy_wait_ms()` which is a tight loop to delay in the reset portion.
Fixes #1486
=> Fix serial reset hang under FreeRTOS

libraries/AudioBufferManager/src/AudioBufferManager.cpp
The ABM had an off-by-one error in the DMA buffer swapover.  Instead of setting the DMA address to the newly added buffer in active[], it set it to the buffer that was currently running.
This would effectively disable the ping-pong and cause clicks/lost data.
Fixes #1491
=> AudioBufferManager(I2s, PWMAudio, ADCInput) xover

libraries/AudioBufferManager/src/AudioBufferManager.cpp
**AudioOutputPWM** method from [ESP8266Audio](https://github.com/earlephilhower/ESP8266Audio) library plays very first audio file just fine,
but gets stuck on a second one.
This is the gdb batcktrace:
```
(gdb) bt
#0  dma_channel_get_irq0_status (channel=3)
at /home/user/Arduino/hardware/pico/rp2040//pico-sdk/src/rp2_common/hardware_dma/include/hardware/dma.h:633
#1  AudioBufferManager::_irq ()
at /home/user/Arduino/hardware/pico/rp2040/libraries/AudioBufferManager/src/AudioBufferManager.cpp:281
#2  0x20000cb8 in irq_handler_chain_slots ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```
It was found out that the issue is caused by ~AudioBufferManager() destructor that have not freed the irq resource properly after the first run.
This commit fixes the …
=> fix for invalid __channelCount in ~AudioBufferManager()

libraries/ADCInput/src/ADCInput.cpp, libraries/PWMAudio/src/PWMAudio.cpp
Handle the case where the DMA manager is unable to completely allocate needed resources (DMA channels or memory) and return `false` in ::begin()
=> Addition ABM checks in PWMAudio and ADCInput

cores/rp2040/PIOProgram.cpp, cores/rp2040/PIOProgram.h, cores/rp2040/RP2040Support.h, cores/rp2040/main.cpp
Rewrite the PIOProgram helper class to properly re-use loaded programs and to try to re-use loaded instructions before allocating a new PIO program.
Supersedes #1524
=> Enable proper reuse of PIO programs

libraries/I2S/src/I2S.cpp
IMHO _isHolding should not be considered in available() when I2S is an output.
Because:
1. not all write methods use _holdWord. If only write(int32, bool) or write(uint8_t, size_t) are used, available() always returned 4 bytes too many.
2. If _arb->available() == 0, but there is space in _holdWord, and you write enough to fill _holdWord, then 4 Bytes get written to _arb. This would block. 
With this fix it's always guaranteed that you can write the amount of bytes that available() returned without it getting blocked.
It *might* be possible to sometimes write more. (If there is space in _holdWord or if a buffer finished playing since available() was called.)
MCVE for scenario 1:
Without this patch: LED never turns on because available() never returns 0.
With this patch: LED turns on. …
=> Fix: I2S::available() returning too many bytes

docs/fs.rst
Example code for [`info64`](https://arduino-pico.readthedocs.io/en/latest/fs.html#info64) has the incorrect function calls
=> fix typo in fs.rst regarding info64

libraries/I2S/src/I2S.h
Regression in #1555 
```
C:\Users\linus\Projekte\arduino-pico\libraries\I2S\src/I2S.h:26:7: note: 'I2S& I2S::operator=(const I2S&)' is implicitly deleted because the default definition would be ill-formed:  
26 | class I2S : public Stream {
|       ^~~
C:\Users\linus\Projekte\arduino-pico\libraries\I2S\src/I2S.h:26:7: error: non-static const member 'const int I2S::I2SSYSCLK_44_1', cannot use default assignment operator
C:\Users\linus\Projekte\arduino-pico\libraries\I2S\src/I2S.h:26:7: error: non-static const member 'const int I2S::I2SSYSCLK_8', cannot use default assignment operator
*** [.pio\build\rpipicow\src\main.cpp.o] Error 1
```
Making them static seems obvious to me, but I'm not sure if my fix is "best practice". If you have any other idea, feel free to do that. 
Context, why I …
=> fix: 'I2S::operator=(const I2S&)' is implicitly deleted (#1555)

libraries/Wire/src/Wire.cpp
When we swap the Wire objects, we need the i2c0 IRQ shim to call Wire1.onIRQ, not the usual Wire.onIRQ.  Same for i2c1 IRQ shim.
Fixes #1607
=> Handle swapped Wire IRQs properly

tools/platformio-build.py
Fixes issues observed in https://github.com/earlephilhower/arduino-pico/discussions/1615.
The `_idedata` has been changed to `__idedata` in newer PlatformIO core versions per https://github.com/platformio/platformio-core/commit/158aabbdf23ed1ff8f5e3f01fb4ef1723a78d3bb, first shipped in PIO core [v6.1.5](https://github.com/platformio/platformio-core/releases/tag/v6.1.5). This change has broken the logic to expand out the `-iprefix PATH @INCLUDEFILE` argument into its individual include paths, causing Intellisense breakages on some VSCode systems and other IDEs that didn't handle these arguments correctly or in which the path was corrupted.
This patch still has backwards compatibaility with older PlatformIO core versions since it checks for `idedata`, `_idedata` and `__idedata`.
=> Fix PlatformIO intellisense

platform.txt
Requiring the auto-discovery tool and serial monitor if they have not already been included by other boards (namely if AVR cores have been uinstalled in the IDE).
=> Update platform.txt to require auto-discovery and serial-monitor

libraries/SPI/src/SPI.cpp
1. I think in the first log line, you want to log the parameters with which beginTransaction() got called, and not the old settings. (_spis are the previous settings)
2. I wanted to see which baudrate was actually set. The compiler optimizes `actualBauds` away if logging is disabled, right?
=> SPI debugging: tiny fix & log actual baudrate

docs/license.rst
Hi all,
I was reading the licensing information and noticed a small typo.
Simple fix, forgot the n on "Corporation".
Thanks,
Matt
=> Fixed typo in docs/license.rst

libraries/LEAmDNS/src/LEAmDNS_Control.cpp
ip_addr_t has different structure with LWIP_IPV6 enabled. This fix makes it compile, but doesn't enable MDNS over IPv6.
=> Make it compile with IPv6 enabled

cores/rp2040/SerialUART.cpp, libraries/SPI/src/SPI.cpp, libraries/Wire/src/Wire.cpp
Setting a pin to the current value is a no-op, not fatal.
Fixes #1652
=> Allow re-setting identical pins without panic()

cores/rp2040/RP2040USB.cpp, cores/rp2040/RP2040USB.h, libraries/Joystick/src/Joystick.cpp, libraries/Keyboard/src/Keyboard.cpp, libraries/Mouse/src/Mouse.cpp
Fixes #1682
Make the HID report wait up to 500ms for an existing one to go out before giving up sending a report.
=> Ensure HID reports aren't dropped

ota/make-ota.sh
It seems it was using the system wide install I had in the past.
This change makes the paths consistent with `make-libpico.sh`
https://github.com/earlephilhower/arduino-pico/blob/0b56452c353e4fc5c8c0bd8e4383c2dc2d0a49c6/tools/libpico/make-libpico.sh#L5-L6
=> Fix gcc search path in make-ota.sh

platform.txt
For some reason `program ... reset" causes OpenOCD to leave the chip in a state where the 2nd core does not come up properly, leading to problems in FreeRTOS and others.
Use a separate reset sequence after programming to work around the issue.
Fixes #1687
=> Fix PicoProbe CMSIS restart of second core

cores/rp2040/lwip_wrap.cpp
When built for the PicoW but ron on a Pico (non-W), fall through to use the wired Ethernet mutex instead of no mutex at all for LWIP protection.
=> Fallthrough LWIP mutex on PicoW wired Ethernet

libraries/SPI/keywords.txt, libraries/SPI/src/SPI.cpp, libraries/SPI/src/SPI.h
Fixes #1147
When SPI.beginTrqansaction() is called, disable all GPIO IRQs that were registered using SPI.usingInterrupt().  On SPI.endTransaction(), restore all the IRQs to their prior state.
=> Support IRQ disabled SPI transactions

README.md, docs/spi.rst, libraries/SPI/src/SPI.h, libraries/SPISlave/examples/SPItoMyself/SPItoMyself.ino, libraries/SPISlave/keywords.txt, libraries/SPISlave/library.properties, libraries/SPISlave/src/SPISlave.cpp, libraries/SPISlave/src/SPISlave.h, tests/restyle.sh
Allows the Pico to behave as an SPI slave and allows apps to respond with appropriate data through callbacks.
Fixes #1680
=> Add SPISlave class

package/package_pico_index.template.json
See https://github.com/earlephilhower/pico-quick-toolchain/issues/30 Fixes #1711
=> Fix Windows GDB startup with new toolchain binary

cores/rp2040/main.cpp, docs/bearssl-server-secure-class.rst, docs/multicore.rst, libraries/Joystick/examples/Joystick-AllFunctions/Joystick-AllFunctions.ino, libraries/JoystickBLE/examples/BLEJoystick-AllFunctions/BLEJoystick-AllFunctions.ino, libraries/JoystickBT/examples/BTJoystick-AllFunctions/BTJoystick-AllFunctions.ino, libraries/lwIP_w5500/src/utility/w5500.h
Fixes #1749
Defining a global true `bool core1_separate_stack = true` will separate the two cores' stacks, with core 0 using the scratch RAM while core 1 will use 8K from the heap.
=> Allow full 8K stack for both cores, optionally

libraries/SPI/src/SPI.cpp
With HW chip select enabled, transfer16's 2 individual byte transfers will actualy deassert CS for a brief instant between bytes.  Avoid this by doing a single multi-byte (2) tranfer of 16b.
=> Don't break transfer16 intop 2 8-bit CS periods

cores/rp2040/RP2040USB.cpp, docs/usb.rst
Fixes #1769
Add a weak variable that can be overridden by the user to speed up or slow down the USB HID polling speed.
=> Allow changing USB HID poll rate

libraries/EEPROM/src/EEPROM.cpp
Committing to flash doesn't clear the `_dirty` variable, so if `EEPROM.commit()` is called a second time, it will write the data again to flash even with no changes in the data since the previous commit.
=> Clear dirty flag after commiting EEPROM to flash

cores/rp2040/posix.cpp
Use __attribute((weak)) for _write() and other stubs called by newlib, so that sketch and library code can provide non-stub implementations, as they can do in other Arduino cores
=> Use __attribute((weak)) for _write() and other stubs called by newlib

docs/fs.rst
The filesystem documentation contains a few typos. This PR fixes the ones I've noticed.
=> Fix typos in fs.rst

cores/rp2040/SerialUSB.cpp, cores/rp2040/SerialUSB.h, docs/serial.rst
Adds some more functionality present in other Arduino cores, allowing more fine-grained control over what to do when the USB host closes the connection or wants to indicate an EOF condition.
(C programmer disclaimer: any resemblance to an actual C++ programmer living or dead is purely coincidental, I have no idea whether the methods being added to the .h file should be virtual and/or override or any other such combination, feedback and mods to the PR welcome)
=> add Serial.dtr() and Serial.rts() methods

libraries/I2S/src/I2S.cpp
=> Allow MCLK multiplier to be set on all I2S devices

libraries/lwIP_Ethernet/src/LwipIntfDev.h
std::bind can cause a memory allocation to occur during the periodic polling interrupt which is a very bad thing.  Use a lambda instead.
Fixes #1812
=> Avoid memory allocation in Ethernet callbacks

libraries/HID_Bluetooth/src/PicoBluetoothBLEHID.h
If the BLE connection is severed, don't wait for the needToSend flag to clear in the HID::send routine since it may never actually clear unless the BLE connection is restored.
Partial #1817
=> Avoid infinite loop in BLE HID send

package/package_pico_index.template.json
=> Fix picotool path for Windows and Mac

cores/rp2040/wl_definitions.h
Arduino's new WiFiS3 library added ENC_TYPE_WPA, ENC_TYPE_WPA2 and ENC_TYPE_WPA3
so this PR updates wl_enc_type in this core
=> wl_defintions.h wl_enc_type update

libraries/lwIP_Ethernet/src/LwipIntfDev.h
LwipIntfDev - hostByName default value for the timeout parameter to have standard version with two parameters. I used the default 15000 as in WiFiClass
=> LwipIntfDev - hostByName default value for the timeout parameter

libraries/WiFi/src/WiFiClass.cpp, libraries/lwIP_Ethernet/src/LwipIntfDev.h
The 'config' functions with not all parameters specified should use default values for gw IP, subnet mask and DNS server IP. The first Arduino Ethernet library has this (with begin), I guess the first Arduino WiFi library  had it too, but the default values were implemented in the firmware. Then WiFi101 and WiFiNINA are written base on WiFi lib's source code, but without the defaults implemented in firmware. (My PR are waiting to fix that.) The new [WiFiS3](https://github.com/arduino/ArduinoCore-renesas/blob/main/libraries/WiFiS3/src/WiFi.cpp#L151) and WiFiC3 libraries by Arduino have it right.
This PR adds the default values for gateway, subnet mask and DNS. The solution in LwipIntfDev is the same as in ESP8266 core. And the WiFi library now redirects all versions of `config` to …
=> WiFi and Ethernet - config static IP auto gw,mask,dns as in Arduino libs

libraries/lwIP_Ethernet/src/LwipIntfDev.h
when I wrote the test sketch for WiFi libraries I wanted to do `begin` with DHCP, then `begin` with static IP and then again `begin` with DHCP.  I thought that `disconnect()` should clear the static IP for return to DHCP, but it turned out that all libraries I tested  preserved the static IP settings over disconnect() (except my WiFiEspAT). [I learned](https://github.com/esp8266/Arduino/pull/9020#issuecomment-1806789080) that the right way to return to DHCP is `config(0)` or `config(INADDR_NONE)`. And this really worked in all libraries and in modern Ethernet libraries (the ones with `config`) too.
So the user of the library can config the static IP and then `disconnect` and later `begin` again with the same static IP.
Now WiFiTest and ModernEthernetTest do an additional begin/disconnect …
=> LwipIntfDev - disconnect()/end() should not clear static IP settings

libraries/WebServer/src/WebServerTemplate.h, libraries/WiFi/examples/WiFiServer/WiFiServer.ino, libraries/WiFi/src/WiFiServer.cpp, libraries/WiFi/src/WiFiServer.h, libraries/WiFi/src/WiFiServerSecureBearSSL.h
In new (this year's) WiFi libraries by Arduino in the Renesas Core they finally enhanced the WiFiServer API so now we know that the preferred method name to stop the server is `end`.  They added `begin` with parameter `port` which goes with a constructor without parameter. 
op bool for Server originates in the Ethernet library 2018 update.
And I recommend to mark method `available()` as deprecated. Users should be educated to use `accept()` as this is the correct name for that implementation.
=> WiFiServer modernization

libraries/LEAmDNS/src/LEAmDNS_Helpers.cpp
When running Wi-Fi on the Pico W for a longer time, I hit a FreeRTOS fatal error due to memory allocation by `std::bind` in `MDNSResponder` (see the callstack below). I therefore applied the same fix as in #1815 and have not seen it happening since.
Maybe the same should be done for the remaining `std::bind` in ArduinoOTA?
```
sleep_until@0x1004ff3e (/sleep_until.dbgasm:43)
sleep_us@0x1004ff9c (/sleep_us.dbgasm:15)
sleep_ms@0x1004ffb6 (/sleep_ms.dbgasm:8)
rtosFatalError@0x1004a610 (~/.platformio/packages/framework-arduinopico/libraries/FreeRTOS/src/variantHooks.cpp:339)
xQueueSemaphoreTake@0x10048608 (~/.platformio/packages/framework-arduinopico/libraries/FreeRTOS/lib/FreeRTOS-Kernel/queue.c:1486)
xQueueTakeMutexRecursive@0x10048750 …
```
=> Replace `std::bind` in `MDNSResponder` for UDP context

libraries/FreeRTOS/src/variantHooks.cpp
I encountered an issue similar to the one in #1868, but this one is way more unlikely to happen. I believe what happens is similar to what you suspected in https://github.com/earlephilhower/arduino-pico/issues/1868#issuecomment-1836761063. When `core0` wants to idle `core1`, it waits forever in `while (!__otherCoreIdled)` since at that time `core1` is in an ISR, acquiring a lock (see the callstacks of both cores below). Therefore, I’ve moved `portDISABLE_INTERRUPTS` up in `IdleThisCore` and with this it’s been running for 11 hours straight without occurring. 
I’m not sure if this guarantees that it cannot happen anymore, but it should at least lower the chance.
**Callstack `core0`:**
```
__freertos_idle_other_core@0x20000120 (~/.platformio/packages/framework-arduinopico/libraries/FreeRTOS/ …
```
=> Disable interrupts first when idling core

variants/generic/common.h
so those libraries which rely on it can detect and use Wire1. e.g. u8g2 will not use Wire1 unless this is (a) defined and (b) >1. This constant is defined on other cores, e.g. for SAMD based boards.
This should resolve situations like that reported in #1182.
I am not entirely sure if `WIRE_INTERFACES_COUNT` should be defined in `common.h`, as in other cores it is defined in variant-specific headers, e.g.
https://github.com/search?q=repo%3Aarduino%2FArduinoCore-samd%20WIRE_INTERFACES_COUNT&type=code
However given that `generic/pins_arduino.h` defines pins for both I2C0 and I2C1, this doesn't seem unreasonable. i.e. the generic variant already assumes the presence of 2 I2C peripherals.
=> Adds definition for WIRE_INTERFACES_COUNT #1182

docs/install.rst, package/package_pico_index.template.json
Fixes #1919 by using binaries from https://github.com/earlephilhower/pico-quick-toolchain/pull/37
=> Update Mac Picotool/OpenOCD to use bundled dylibs

libraries/WiFi/src/utility/lwIP_nodriver.h
fixes https://github.com/earlephilhower/arduino-pico/issues/1965
the error is from my "prepare for alternative drivers" PR and it affects compilation for wired Ethernet with boards other than Pico W
=> lwIP_nodriver - end() compilation error fix

libraries/SPI/src/SPI.cpp
Clocks were not being set at all after #1934.  Ensure they are by initting to an impossible 0hz clock on creation and ::end
Fixes #1969
=> Fix initial SPI startup

package/package_pico_index.template.json
All binaries should now be native on Apple silicon.
=> Make OpenOCD and Picotool M1 native, too

libraries/lwIP_Ethernet/src/LwipEthernet.cpp, libraries/lwIP_Ethernet/src/LwipIntfDev.h
Fixes #1973
The periodic LWIP pump/Ethernet packet reader async_context stopped firing occasionally under high packet loads, causing the LWIP stack to become unresponsive to any incoming data.
Re-implement the 2-step process for polling (like the CYW43 driver from the RPI folks does) and undoes #1864 change.
=> Undo #1864, fix LWIP offline error

cores/rp2040/lwip_wrap.cpp, docs/ethernet.rst, libraries/lwIP_Ethernet/src/LwipEthernet.cpp, libraries/lwIP_Ethernet/src/LwipEthernet.h, libraries/lwIP_Ethernet/src/LwipIntfDev.h, libraries/lwIP_enc28j60/src/utility/enc28j60.cpp, libraries/lwIP_enc28j60/src/utility/enc28j60.h, libraries/lwIP_w5100/examples/WiFiClient-W5100/WiFiClient-W5100.ino, libraries/lwIP_w5100/src/utility/w5100.cpp, libraries/lwIP_w5100/src/utility/w5100.h, libraries/lwIP_w5500/src/utility/w5500.cpp, libraries/lwIP_w5500/src/utility/w5500.h
No polling needed and should reduce latency by using the GPIO interrupt to signal the Pico to read a received packet.
=> Add W5100, W5500, and ECN28J60 interrupt-driven mode

libraries/lwIP_w5100/examples/WiFiClient-W5100/WiFiClient-W5100.ino
Use the #define board name to identify when building for the WIZnet W5100s-EVB-Pico and assign the proper pins and IRQs.
=> Make W5100 example run on Wiznet w/no changes

libraries/PWMAudio/src/PWMAudio.cpp, libraries/PWMAudio/src/PWMAudio.h
When using low bitrates like 8000hz or 11025hz as example, PWMAudio will produce a high pitched whine(same as sample rate hz), that sometimes can overwhelm the audio.
This is because the DMA transfers (sample rate) are synced to the PWM wave generation (pwm frequency).
In the RP2040 datasheet under DMA 2.5.5.1, there is a section about pacing timers.
This is a timer that triggers the DREQ every n clock_sys ticks.
Now this is replacing the PWM synced method, which allows the PWM wave generation to have a different frequency than the sample rate.
There is one downside;
The begin() function CAN take quite a few milliseconds worst case to find the perfect fraction for the pacing timer. As the pacer has to be configured with a numerator and a denominator.
It has to find the right fraction …
=> Low bitrate whine fix (DMA pacing timer)

libraries/lwIP_ESPHost/src/lwIP_ESPHost.cpp
WiFiMulti specifies a specific BSSID, in addition to the AP name and password.  In the WiFi core the BSSID is stored as the raw 6-byte MAC address, but the ESPHostedFG firmware expects a formatted C-String (i.e. "ab:cd:ef:01:02:03" instead of {0xab, 0xcd, 0xef, 1, 2, 3})
Convert the raw bytes to the string format expected in the ESP FW.
=> Fix WiFiMulti and ESPhost STA connection w/BSSID

cores/rp2040/lwip_wrap.cpp
Remove the HW random generator call while initting LWIP to avoid the SDK looping forver due to FreeRTOS exception/timer interrupts.
=> Can't call get_rand_64 under FreeRTOS

libraries/lwIP_ESPHost/src/lwIP_ESPHost.cpp
See https://github.com/earlephilhower/arduino-pico/pull/2001#issuecomment-1944461469
=> Fix ESPHost WiFi connect without a specified BSSID

libraries/lwIP_ESPHost/src/ESPHost.cpp, libraries/lwIP_ESPHost/src/ESPHost.h, libraries/lwIP_ESPHost/src/lwIP_ESPHost.cpp, libraries/lwIP_ESPHost/src/lwIP_ESPHost.h
I attempt to make the ESPHost work with interrupt. There are two problems.
First problem is small. The DATA_READY pin is active HGH with esp_hosted. So we need a way to return from RawDev the state for interrupt.
Second problem is big. The semaphores don't work. It is a problem without the interrupt too, but with the interrupt version `handlePackets` doesn't run in async_context so there is no locking.
`ethernet_arch_lwip_begin/end` only guards code executed within async_context so using it elsewhere doesn't stop the code executing. It only blocks handlePackets if executed from the timer worker.
=> lwIP_ESPHost - using interrupt

libraries/lwIP_enc28j60/src/utility/enc28j60.cpp, libraries/lwIP_enc28j60/src/utility/enc28j60.h
RawDev::end() is used in LwipIntfDev::end().
=> lwIP_enc28j60 - add missing end() method

libraries/lwIP_Ethernet/src/LwipIntfDev.h
all Ethernet libraries have `linkStatus`. 
https://github.com/JAndrassy/Arduino-Networking-API/blob/main/ArduinoNetAPILibs.md#ethernet-network-interface
all code in this PR copied from esp8266 core without changes.
tested with the [ModernEthernetTest](https://github.com/JAndrassy/NetApiHelpers/blob/master/examples/ModernEthernetTest/ModernEthernetTest.ino)
=> LwipIntfDev - linkStatus() added

libraries/lwIP_enc28j60/src/utility/enc28j60.cpp, libraries/lwIP_w5500/src/utility/w5500.h
=> Protect W5500/ENC28J60 isLinked() call from IRQ-mode

libraries/I2S/src/pio_i2s.pio, libraries/I2S/src/pio_i2s.pio.h
=> Shift I2S input data by 1 bit

libraries/BTstackLib/src/BTstackLib.cpp
Hi,
The call to `le_device_db_init()` seems to superfluous as it is called in the subsequent `sm_init()`. It is not present in BTstack examples I've seen, for example:
https://github.com/bluekitchen/btstack/blob/72ef1732c954d938091467961e41f4aa9b976b34/example/le_streamer_client.c
Removing has no apparent effects (good or bad) in my projects.
Best regards,
djpearman
=> BTstack: remove superfluous call during setup.

cores/rp2040/lwip_wrap.cpp, lib/platform_wrap.txt, libraries/lwIP_Ethernet/src/LwipIntfDev.h
As seen in debug of #2149, if the LwipIntfDev is already _started, return false for a ::begin() call.
Also, protect netif_add/_remove on the very small possibilty of being called by LwipIntfDev devices while the CYW43 driver is doing work.
=> Protect againt calling LWIP_Ethernet::begin twice

libraries/lwIP_Ethernet/src/LwipIntfDev.h
When a ping is sent from the Pico, a raw_recv callback is added which sees all raw incoming packets to detect the response from the ping target. If while waiting for the target response an external ping packet arrives this incoming ping request packet will be processed by the LwipIntfDev<>::_pingCB which will return "0" not processed and which *should* not change the payload unless it handles the actual packet.
Unfortunately, the 20 byte header was unconditionally stripped off of the packet before checking if this was our response, changing the payload address and causing an assertion in LWIP.
Fix by using absolute offsets inside the raw packet for the ping response checks.
Fixes #2156
Fixes #2149
=> Fix LWIP crash on unexpected ping packets

libraries/WebServer/src/Parsing.cpp
From https://github.com/espressif/arduino-esp32/pull/9594
~128 bytes lower usage
=> Small RAM savings in WebServer

libraries/WebServer/examples/UploadHugeFile/README.md, libraries/WebServer/examples/UploadHugeFile/UploadHugeFile.ino, libraries/WebServer/src/HTTPServer.h, libraries/WebServer/src/Parsing.cpp, libraries/WebServer/src/WebServerTemplate.h, libraries/WebServer/src/detail/RequestHandler.h, libraries/WebServer/src/detail/RequestHandlersImpl.h
From https://github.com/espressif/arduino-esp32/pull/9440
=> Allow uploading huge files to WebServer

libraries/WebServer/src/Parsing.cpp
From https://github.com/espressif/arduino-esp32/pull/9167
=> Fix POST form parser edge cases

libraries/HTTPClient/src/HTTPClient.cpp, libraries/HTTPClient/src/HTTPClient.h
From:
https://github.com/espressif/arduino-esp32/pull/6216
https://github.com/espressif/arduino-esp32/pull/6280
https://github.com/espressif/arduino-esp32/pull/7112
=> Add Cookies to HTTPClient

libraries/AudioBufferManager/src/AudioBufferManager.cpp, libraries/BluetoothAudio/examples/A2DPSink/A2DPSink.ino, libraries/BluetoothAudio/src/A2DPSink.cpp, libraries/BluetoothAudio/src/A2DPSink.h, libraries/BluetoothAudio/src/A2DPSource.cpp, libraries/BluetoothAudio/src/A2DPSource.h, libraries/BluetoothAudio/src/BluetoothAudio.h, libraries/BluetoothAudio/src/BluetoothHCI.cpp, libraries/BluetoothAudio/src/BluetoothLock.h
Fixes #2188
We get a call to stop the audio channel from a timer/IRQ context, so can't safely remove the IRQ handler for the AudioBufferManager.  The SDK will panic.
Because the IRQ handler will be a noop if it's not uninstalled, we will instead just leave our shared handler in place and let it do nothing.
Use a common BluetoothLock RAII in BluetoothAudio to clen up the code and automatically lock BT for the AVRCP button methods.
=> Fix crash on audio end from IRQ, refactor A2DP

libraries/LittleFS/src/LittleFS.h, libraries/LittleFS/src/lfs.c, libraries/LittleFS/src/lfs_util.c
Support 255 character names, not just 32, in LittleFS filesystems.
=> Make LittleFS filenames support full size

libraries/BluetoothHIDMaster/examples/KeyboardPiano/KeyboardPiano.ino, libraries/BluetoothHIDMaster/keywords.txt, libraries/BluetoothHIDMaster/library.properties, libraries/BluetoothHIDMaster/src/BluetoothHIDMaster.cpp, libraries/BluetoothHIDMaster/src/BluetoothHIDMaster.h, tests/restyle.sh
Adds BluetoothHIDMaster and HIDKeyStream which let the PicoW connect to and use Bluetooth Classic HID devices like keyboards and mice.
An example that lets the PicoW use a BT keyboard as a piano is included and shows the use of the new classes.
=> Bluetooth Master HID and musical keyboard example

libraries/PWMAudio/src/PWMAudio.cpp
PWMAudio was only ever writing one half the buffer passed in because of an off-by-2 error.  Fixes the sine output in KeyboardPiano.
=> Fix PWMAudio::write(buffer, len)

libraries/BluetoothAudio/src/BluetoothAudioConsumerI2S.cpp, libraries/BluetoothAudio/src/BluetoothAudioConsumerPWM.cpp
Around 2x the performance, and every bit is needed w/BT SBC compression and decompression.
=> Use block writes for BT audio consumers

README.md, libraries/BluetoothHIDMaster/examples/KeyboardPiano/KeyboardPiano.ino, libraries/BluetoothHIDMaster/examples/KeyboardPianoBLE/KeyboardPianoBLE.ino, libraries/BluetoothHIDMaster/keywords.txt, libraries/BluetoothHIDMaster/src/BluetoothHIDMaster.cpp, libraries/BluetoothHIDMaster/src/BluetoothHIDMaster.h
Play games on your Pico using Bluetooth gamepads!
=> Add joypad HID master support

docs/bluetooth.rst, docs/fs.rst, docs/hidmaster.rst, docs/index.rst
Also link in FatFSUSB docs, d'oh!
=> Add BluetoothHIDMaster documentation

docs/hidmaster.rst, libraries/BluetoothHIDMaster/examples/KeyboardPiano/KeyboardPiano.ino, libraries/BluetoothHIDMaster/examples/KeyboardPianoBLE/KeyboardPianoBLE.ino, libraries/BluetoothHIDMaster/src/BluetoothHIDMaster.cpp, libraries/BluetoothHIDMaster/src/BluetoothHIDMaster.h
Matches existing library names and nomenclature
=> For consistency, BTHID Joypad->Joystick

docs/hidmaster.rst, libraries/BluetoothAudio/src/A2DPSource.h, libraries/BluetoothHCI/src/BluetoothDevice.h, libraries/BluetoothHCI/src/BluetoothHCI.cpp, libraries/BluetoothHCI/src/BluetoothHCI.h, libraries/BluetoothHIDMaster/src/BluetoothHIDMaster.cpp, libraries/BluetoothHIDMaster/src/BluetoothHIDMaster.h
Bluetooth operates at IRQ level, so using std::list (which needs to new and delete objects) is not legal.  Use a fixed, preallocated vector instead.
=> Avoid malloc/free while in HCI callbacks

libraries/SD/src/SD.h
=> Fix crash on SD.end() without initial SD.begin()

libraries/WebServer/examples/Filters/Filters.ino, libraries/WebServer/src/HTTPServer.cpp, libraries/WebServer/src/HTTPServer.h, libraries/WebServer/src/Parsing.cpp, libraries/WebServer/src/detail/RequestHandler.h, libraries/WebServer/src/detail/RequestHandlersImpl.h
This PR implements filters and removable routes in RP2040 arduino core, making it API compatible with recent changes to ESP32 & ESP8266 WebServer API.
> [!NOTE]
> Please merge when all ESP32 repo pull requests mentioned below are merged.
- https://github.com/espressif/arduino-esp32/pull/9832
- https://github.com/espressif/arduino-esp32/pull/9842
- https://github.com/espressif/arduino-esp32/pull/9851
- https://github.com/esp8266/Arduino/pull/9152
__Noteable Changes:__
1. Request Filters (`setFilter`)
2. Removable Routes (`removeRoute`, `removeHandler`, `_removeRequestHandler`)
=> feat: Implemented support for filters and removable routes in WebServer

libraries/Ticker/src/Ticker.cpp
A Timer is not active after the alarm fires once, so clear the alarm ID so we know we're not running.
=> On Timer::once execution, delete the alarm_id

libraries/HID_Bluetooth/src/PicoBluetoothBLEHID.h, libraries/HID_Bluetooth/src/PicoBluetoothHID.h
Fixes #2251
The 2-phase send could get out of whack if transmission was attempted when no device was connected. Clear things up so if things aren't connected, then no data gets set as pending.
=> Avoid deadlock BT/LE HID send when disconnected

tools/platformio-build.py
An oversight in the order of updating the ASFLAGS with a copy of the CCFLAGS (see line 110) and then updating the CCFLAGS (without resyncing the ASFLAGS) leads to a fatal compilation error in the [Adafruit PicoDVI](https://github.com/adafruit/PicoDVI) library, in which `tmds_encode.S` fails to find the `pico/config.h` include file. This fix updates the ASFLAGS manually after changing the CCFLAGS so that they're equal again, and the library can be compiled.
Failure reported in https://community.platformio.org/t/anybody-know-how-to-fix-this-this-is-an-error-for-the-picodvi-library-downloaded-from-platfrom/41607.
(This change only affects assembler files which access include files outside of the already added pico-sdk/src/rp2040/hardware_regs and pico-sdk/src/common/pico_binary_info …
=> Fix includes for assembler files in PlatformIO build

libraries/HTTPClient/src/HTTPClient.h, libraries/WiFi/src/WiFiClientSecureBearSSL.cpp
Fixes #2254
The faked certificate was allocated but not deleted in certain cases.  Make sure to clean up in the destructor.
=> Fix leak in HTTPSClient

variants/adafruit_feather/pins_arduino.h, variants/adafruit_itsybitsy/pins_arduino.h, variants/generic/common.h
Fix D pins mapping on Adafruit itsybitsy RP2040 and Adafruit Feather RP2040
=> Fix D pins mapping on Adafruit IB RP2040

tools/makeboards.py
The repo and development use only '\n' (UNIX) EOLs.  When a user runs makeboards on a Windows system they end up changing every line in boards.txt and the JSON files to Windows '\r\n' format.
Explicitly set the newline character when opening the output files to avoid this.
=> Ensure makeboards.py writes UNIX newlines

cores/rp2040/RP2040USB.cpp, libraries/Joystick/docs/api.md, libraries/Joystick/examples/Joystick-AllFunctions/Joystick-AllFunctions.ino, libraries/Joystick/examples/Joystick16Bit/Joystick16Bits.ino, libraries/JoystickBLE/src/JoystickBLE.cpp, libraries/KeyboardBLE/src/KeyboardBLE.cpp, libraries/MouseBLE/src/MouseBLE.cpp
Fixes #2275
Adds `Joystick.use10bit` and `Joystick.use16bit` methods.  10-bit is unsigned from 0...1023 while 16-bit is signed -32767..32767. Defines a new HID descriptor to support the increased resolution.
=> Add true 10- and 16-bit joystick modes

.github/workflows/pull-request.yml, tests/restyle.sh
Variant builds were taking longer than the actual individual CI jobs, so split it up.
Compile the spelling and style checks, they ran very fast and spent more time in checking out than in running.
=> Split variant build, combine spell + style checks

libraries/HID_Bluetooth/src/HID_Bluetooth.cpp
Underlying HID_Joystick now always using 16-bit format axes, need to update BT and BLE descriptors sent to the BT master or it will misinterpret the reports and the reported joystick state will be read as garbage.
Fixes bug introduced in #2276, oops!
=> Fix BT/BLE Joystick reports

libraries/HTTPClient/src/HTTPClient.h
Found via #2296, the HTTPClient was looking for old ESP8266 defines and not the RP2040 core ones to enable it.  Now dump on `Core` level.
=> Fix HTTPClient debug output

cores/rp2040/sdkoverride/tusb_gamepad16.h, libraries/HID_Bluetooth/src/HID_Bluetooth.cpp
Create a single spot with the gamepad16's HID report descriptor and report structure.  Avoids cut-n-pasted code.
=> Factor out cut-n-pasted GAMEPAD16 HID structures

libraries/lwIP_Ethernet/src/LwipIntfDev.h
From @JAndrassy https://github.com/esp8266/Arduino/pull/9173
=> LwIpIntfDev.end() check _started to prevent crash

libraries/ArduinoOTA/src/ArduinoOTA.cpp, libraries/DNSServer/src/DNSServer.cpp, libraries/HTTPUpdate/src/HTTPUpdate.h, libraries/SD/src/SD.h, libraries/SDFS/src/SDFS.h, libraries/WiFi/src/CertStoreBearSSL.cpp, libraries/WiFi/src/WiFiClientSecureBearSSL.cpp, libraries/WiFi/src/include/UdpContext.h, libraries/lwIP_Ethernet/src/LwipIntfCB.cpp
In ported libraries there were still some remaining DEBUG_ESP_PORT references.  Moved to their RP2040 equivalents.
=> Replace most remaining ESP_ debug macros

cores/rp2040/lwip_wrap.cpp, lib/platform_wrap.txt
Somehow returning the results of a `void` function from another `void` wrapper didn't trigger any warnings.  Also missed tcp_bind actual GCC wrapping.
=> Fix minor LWIP wrapper errors

docs/bearssl-client-secure-class.rst
Hi,
It seems as though the section 'ESP32 Compatibility' is one level too high in the documentation of 'WiFiClientSecure Class'. Lowered to be a subsection thereof and avoid appearing as separate in the contents.
Best regards,
djpearman
=> Documentation: moved 'ESP32 Compatibility' to subsection

libraries/FatFSUSB/src/FatFSUSB.h, libraries/Joystick/src/Joystick.h, libraries/Keyboard/src/Keyboard.h, libraries/Mouse/src/Mouse.h, libraries/MouseAbsolute/src/MouseAbsolute.h, libraries/SingleFileDrive/src/SingleFileDrive.h
The included USB libraries are not compatible with Adafruit TinyUSB, so add a #error message when they're built with the define set.
=> Add checks for Adafruit TinyUSB to USB libs

cores/rp2040/RP2040Support.h, docs/rp2040.rst, libraries/rp2040/examples/DMAMemcpy/DMAMemcpy.ino
RP2040::memcpyDMA implements a DMA-controlled memory copy call identical in function to standard memcpy, but using an onboard DMA engine.  For large memory transfers this can be significantly faster than using the CPU-based memcpy.  Only 4-byte aligned source, destination, and counts are allowed. If any inputs are not 4-byte aligned, then standard memcpy will occur so it will behave correctly for any inputs.
=> Add RP2040.memcpyDMA for DMA-managed memory copies

cores/rp2040/FS.cpp, cores/rp2040/FS.h, cores/rp2040/FSImpl.h, libraries/FatFS/src/FatFS.h, libraries/HTTPUpdateServer/src/HTTPUpdateServer-impl.h, libraries/LittleFS/src/LittleFS.h, libraries/SDFS/src/SDFS.h, libraries/WebServer/examples/FSBrowser/FSBrowser.ino, libraries/WebServer/examples/WebUpdate/WebUpdate.ino
Removed FS::info64, and updates FS::info with the 64-bit version since in 2024 it's almost impossible to get a SD card smaller than 4GB.
Most code can simply replace info64 with info and continue operation, if they were updated to be 64-bit in the first place.
=> BREAKING: Remove FS::info64, make FS::info 64-bit

libraries/lwIP_w6100/src/W6100lwIP.h, libraries/lwIP_w6100/src/utility/w6100.cpp, libraries/lwIP_w6100/src/utility/w6100.h
This is a first WIP for supporting the Wiznet W6100 Ethernet chip in the `lwIP_Ethernet`. 
* It was cloned from the `lwip_5500` driver
* I used the same structure and naming for register access
- Code works on both chips on otherwise identical boards (W5500-EVB-Pico & W610-EVB-Pico): You only have to change the `W5550` to `W6100`  in the generic of the type for the constructor: `ArduinoEthernet<Wiznet6100> Ethernet(17, SPI, 21)`
- Tested: Pinging (~1.7-2.0ms), UDP, TCP (WebServer), ArduinoOTA (espota)
* As of now, both (lwIP_5500 and this lwIP_W6100) cannot run the libraries/WebServer/examples/AdvancedWebServer/AdvancedWebServer.ino due to default stack limits (crashes after few requests because the stack grows too deep. This seems not to be related to any of the Wxx00 drivers but how …
=> W6100 implementation based on W5500 driver

README.md
I'm sorry I missed this out in #2370
=> Adding Cytron IRIC IO Controller to the supported list in README.md

tools/json/challenger_2350_bconnect.json, tools/json/challenger_2350_wifi6_ble5.json, tools/json/sparkfun_promicrorp2350.json, tools/makeboards.py, tools/platformio-build.py
Was used in linkerscript and `boards.txt` but not available to PlatformIO.
Docs will be updated separately after verification.
=> Update PIO board definition for PSRAM

README.md, boards.txt, lib/rp2040/picodebug.tcl, package/build_boards_manager_package.sh, platform.txt, tools/makeboards.py, tools/platformio-build.py
Pico-Debug is no longer supported and was removed from OpenOCD, so remove the references and upload menu items for it.
Fixes https://github.com/earlephilhower/pico-quick-toolchain/issues/61
=> Remove pico-debug because it's archived

cores/rp2040/SerialPIO.cpp, cores/rp2040/SerialPIO.h, cores/rp2040/SerialUART.cpp, cores/rp2040/SerialUART.h, cores/rp2040/SoftwareSerial.h, cores/rp2040/pio_uart.pio, cores/rp2040/pio_uart.pio.h, docs/piouart.rst, docs/serial.rst, keywords.txt
Use real GPIO pad inversion to allow inverted RX, TX, and controls for the hardware UART and software PIO-emulated serial ports.
Adds ``setInvertTX(bool)`` and ``setInvertRX(bool)`` calls to both ports, with ``setInvertControl(bool)`` for the HW UARTS.
=> Add serial inversion for UART and SerialPIO

docs/fs.rst
FSInfo64 removed and FSInfo updated. File name length limitation of LittleFS changed to 255 characters
=> FS doc update

libraries/PDM/src/rp2040/pdm.pio.h
tl;dr: I had to uncomment the `pio_gpio_init` for the PDM mic data in pin in the PDM library to make code which previously worked on an RP2040 also work on an RP2350.  The modified library also still works with the RP2040 in my project.
Details:
I am using the PDM library to read a [PDM microphone](https://www.adafruit.com/product/4346).  I developed my code on a RP2040 Pico.  It is working correctly.
I recently obtained my first [RP2350 board](https://shop.pimoroni.com/products/pimoroni-pico-plus-2), which is intended to be pin-compatible with the Pico.  I plugged it in and my circuit worked, but the PDM mic was reading as a steady -128.  With a scope, I verified that the PDM clock was still being emitted at the right frequency, and the PDM data in pin was being driven by the mic.
It …
=> libraries/PDM/src/rp2040/pdm.pio.h: pio_gpio_init data in pin.

docs/index.rst, docs/rp2350.rst
=> Document E9 non-workaround

variants/solderparty_rp2350_stamp_xl/pins_arduino.h
I saw the define was needed for the PGA2350, so I think it needs to be here as well.
=> solderparty_rp2350_stamp_xl: Properly mark as using RP2350B

libraries/Wire/src/Wire.cpp
This PR handles the timeout in I2C write() function. This avoids hanging in peripheral mode, when replying to a request with more bytes than the controller expects. 
Let me know if any changes are needed ! And thanks for the hard work on this integration :)
=> I2C lib: Handle timeout in write()

libraries/SPI/src/SPI.cpp, libraries/lwIP_Ethernet/src/LwipEthernet.cpp
Allow RP2350B boards to use GPIOs 31+ for the Ethernet HW IRQ line. Also update SPI debug output with the new registers.
=> Allow LWIP Ethernet HW IRQs > 32

tools/platformio-build.py
New to the build system; forgot to also exclude CFG_TUSB_DEBUG from platformio-build.py:
https://github.com/earlephilhower/arduino-pico/blob/5fbda352820bb7476db5a29b1a4076640d018a04/tools/platformio-build.py#L130
=> Also remove CFG_TUSB_DEBUG from platformio-build.py for rp2350 -- fix for #2469

cores/rp2040/malloc-lock.cpp
Several Arduino APIs realloc(NULL) which is legal and equivalent to "malloc()", but the PSRAM logic was placing those malloc calls in PSRAM and not RAM because "0" < RAM_START.
Ensure the realloc address is non-null and before RAM_START before using PSRAM.
=> Don't realloc(nullptr) from PSRAM by default

libraries/Wire/src/Wire.cpp
This feature is described in RP2040 datasheet chapter 4.3.13.1 but not implemented in hardware (see https://github.com/raspberrypi/pico-sdk/issues/1595) 
This commit implements it in software, based on code from the probe() function.
My I2C bus is much more robust with this addition :)
=> I2C lib : implement "bus recovery" feature on timeout reset

libraries/Wire/src/Wire.cpp
As reported by @Rasmusfk in #2455, allow for a longer clock stretch period during probes.
=> Wire probe clock stretch up to 500us

tools/platformio-build.py
The previous ones did not include the `-m..` machine flags when compiling assembly code, leading to linker errors.
Drive-by PR into the WIP riscv PR. Fixes `none.S` compilation and linking.
Wasn't needed for RP2040 files because they have 
```
.cpu cortex-m0plus
.thumb
```
in them to select the `-mcpu` `-mthumb` etc. In any case, this is a sane change to make -- we want other user assembly files to be compiled with the by-default right machine flags.
=> Fix compiling assembly

.github/workflows/pull-request.yml
Should eliminate the need to occassionally delete the cache for PlatformIO.
The cache is still restored at the stard and the state at the end gets cached, so we still retain the speed advantage if nothing changed in the platform.
=> Update PIO platform before compile, add RISC-V PIO build to CI

docs/platformio.rst, tools/platformio-build.py
Supersedes https://github.com/earlephilhower/arduino-pico/pull/2487
Adds documentation for changing USB VID, PID, manufacturer and product.
Updates used macros.
Confirmed working with
```ini
[env]
platform = raspberrypi
framework = arduino
board_build.arduino.earlephilhower.usb_manufacturer = Custom Manufacturer
board_build.arduino.earlephilhower.usb_product = Ultra Cool Product
board_build.arduino.earlephilhower.usb_vid = 0xABCD
board_build.arduino.earlephilhower.usb_pid = 0x1337
[env:picow]
board = rpipicow
```
=> Update PIO USB docs, fixup used VID/PID macros

boards.txt, platform.txt, tools/makeboards.py
Released packages have a post-processing step to allow them to work with IDE installed toolchains.  This was not updated for the RISC-V compiler, so R5 compiles fail under the release IDE package.  Update to call proper compiler path.
Fixes #2510
=> Allow IDE install to call RISC-V compiler

cores/rp2040/RP2040Support.h, docs/rp2040.rst, libraries/rp2040/examples/RestartReason/RestartReason.ino
Add code from @palmerr23 in #1843, slight changes were necessary in order to work and make the compiler happy.
Don't have a debug probe here, so I leave that part as-is, maybe someone finds some time to test it.
=> Add getResetReason() by palmerr23

cores/rp2040/RP2040Support.h
Fixes #2525.
Tested on RISC-V with a debugger to match.
"mv" instruction to move one register's content into another register, see https://projectf.io/posts/riscv-cheat-sheet/#misc-instructions.
=> Fix getStackPointer() to work in RISC-V and ARM mode

.github/workflows/pull-request.yml, docs/platformio.rst
Was still missing in the docs.
=> Document setting the PSRAM size for PlatformIO

libraries/PWMAudio/src/PWMAudio.cpp
Help ensure click-free playback by default. App overide will still be obeyed.
=> Increase default PWMAudio buffer sizes

cores/rp2040/flash_wrapper.cpp, lib/core_wrap.txt
The flash ROM routines seem to overwrite the QMI configuration we set for PSRAM, rendering it unreadable after any erase or write or ID command.
Wrap the 4 flash control functions to preserve the QMI state on the RP2350.  On the RP2040, simply pass through the call.
Fixes #2537
=> Preserve PSRAM QMI interface around flash ops

libraries/LittleFS/src/LittleFS.h
All `DEBUGV` statements in littlefs driver are to report error conditions, except for the statement in `lfs_file_close`.
Removed it for consistency and to suppress useless debug logs.
See also #2542 for a discussion on the topic.
=> Remove DEBUGV for lfs_file_close

cores/rp2040/rp2350-memcpy.S, lib/rp2350/platform_wrap.txt
33% faster for 4K memcpy using DMAMemcyp example
With this assembly:
CPU: 4835 clock cycles for 4K
DMA: 2169 clock cycles for 4K
Using stock Newlib memcpy:
CPU: 7314 clock cycles for 4K
DMA: 2175 clock cycles for 4K
(What's interesting is that if we place this in RAM it's actually slower in this test because the CPU instruction fetch will fight with the data read and write, causing stalls...neat!)
=> Add ARM assembly optimized memcpy for RP2350

cores/rp2040/flash_wrapper.cpp
Fixes #2537
While waiting for a working direct cache flush routine, try and force the cache to evict all PSRAM values by reading a bunch of flash addresses (which share the XIP cache).  This hurts performance when PSRAM is not used, but is required for correctness until we have a working XIP flush.
=> Workaround PSRAM cache invalid'n by reading flash

libraries/FreeRTOS/examples/Multicore-FreeRTOS/Multicore-FreeRTOS.ino, libraries/FreeRTOS/examples/StaticMulticore-FreeRTOS/StaticMulticore-FreeRTOS.ino
The PicoW can't access the LED from core 1, because it is driven by the CYW43 chip, so make sure any blinking is on core 0.
Fixes #2553
=> Update FreeRTOS examples for PicoW

cores/rp2040/wiring_private.cpp
You only need to lock the mutex around the std::map check, not the whole IRQ callback
This is important if you have a time-sensitive interrupt on one of the cores
=> Edited the interrupt dispatcher to not block for too long on interrupt

cores/rp2040/flash_wrapper.cpp
New info from RPI engineers give a slightly better/safer method.
=> Update PSRAM cache flush algorithm

libraries/I2S/src/pio_i2s.pio, libraries/I2S/src/pio_i2s.pio.h
2 changes in pio_i2s.pio (stamped 2584) to delay the transitions on LRCK until the falling edge of BCK.  Only for input mode.  TI ADCs usually prefer that timing.
=> Fixes Issue 2584: delays LRCK to falling edge of BCK in I2S input

libraries/SimpleMDNS/src/SimpleMDNS.cpp, libraries/SimpleMDNS/src/SimpleMDNS.h
As discussed in #2582, this makes SimpleMDNS an even better drop-in replacement for LEAmDNS.
=> SimpleMDNS: let `begin` return a bool

.github/workflows/build-libpico.yml
For logs and artefacts see https://github.com/maxgerhardt/arduino-pico/actions/workflows/build-libpico.yml
Motivation: Build the `libpico*.a` files in CI, so that:
* builds are reproducable (we don't have to rely on users compiling those libraries, if they're using different compilers, may introduce subtle bugs)
* easy to adapt featureset of pico-sdk (e.g.; activate `CYW43_PIO_CLOCK_DIV_DYNAMIC` per https://github.com/earlephilhower/arduino-pico/discussions/2590)
* users have a starting point to also build it / check it locally if they want to.
* eliminates some pain points as e.g. encountered in https://github.com/earlephilhower/arduino-pico/discussions/2549  
* auto-triggers when Pico-SDK config is changed
Open points of discussion:
* What compiler versions to use exactly?
* For ARM I …
=> Build libpico in CI

libraries/lwIP_Ethernet/src/LwipIntfDev.h
Prevent symbol conflicts when including both Wifi.h and cyw43.h
Fixes #2602
=> lwIP_Ethernet: rename copied cyw43 mac function

cores/rp2040/RP2040Support.cpp, cores/rp2040/RP2040Support.h, docs/rp2040.rst
The RP2350 boot ROM seems to randomize memory on a HW reset, including both CPU stacks where we normally stuff the "reset to bootloader" flag. Update the docs and source to remove rp2040.enableDoubleResetBootloader() on RP2350-based boards.
Fixes #2606
=> rp2040.enableDoubleResetBootloader only on RP2040

cores/rp2040/wiring_private.cpp
Replace std::map, which can `new` and `delete` elements of the tree, with a statically allocated array and housekeeping.
Fixes #2622
=> Avoid memory (de)allocation in GPIO ISR handler

libraries/AudioBufferManager/src/AudioBufferManager.cpp, libraries/AudioBufferManager/src/AudioBufferManager.h, libraries/I2S/src/I2S.cpp, libraries/I2S/src/I2S.h, libraries/PWMAudio/src/PWMAudio.cpp, libraries/PWMAudio/src/PWMAudio.h
Like GPIO interrupts, allow the user to pass in a callback data pointer.
=> Add optional callback parameters for I2S/PWMAudio

libraries/SimpleMDNS/src/SimpleMDNS.cpp, libraries/SimpleMDNS/src/SimpleMDNS.h
Fixes #2678
A simple mapping allows for basic service text addition even when using SimpleMDNS and ArduinoOTA.
=> Add MDNS.addServiceTxt() to SimpleMDNS

libraries/AudioBufferManager/src/AudioBufferManager.cpp, libraries/PWMAudio/src/PWMAudio.cpp
If we set the frequency to the same one running, no need to do anything.
=> PWMAudio setFrequency optimization

cores/rp2040/AudioOutputBase.h, libraries/BluetoothAudio/src/A2DPSource.cpp, libraries/BluetoothAudio/src/A2DPSource.h, libraries/I2S/src/I2S.cpp, libraries/I2S/src/I2S.h, libraries/PWMAudio/src/PWMAudio.cpp, libraries/PWMAudio/src/PWMAudio.h
The audio output objects all have the same general necessary configuration calls.  Abstract them out to a generic AudioOutputBase interface class that they will inherit from.  Simplies letting applications use different output channels.
Should be backwards compatible with existing code.
=> Derive playback objects from common AudioOutputBase

docs/i2s.rst, libraries/I2S/src/I2S.cpp, libraries/I2S/src/I2S.h, tools/makeboards.py
Increasing `clk_sys` by another 6 MHz would allow for exact 96 kHz and 192 kHz sampling rates (apart from the ±30 ppm of Pico's 12 MHz crystal itself).
=> Overclock to 153.6 MHz (instead of 147.6 MHz) for I²S 48 kHz sample rate

.github/workflows/pull-request.yml
The MacOS12 runner is dead, so move up to the lowest version still available for CI.
=> Move MacX86 runner up to new minimum spec

libraries/AudioBufferManager/src/AudioBufferManager.cpp, libraries/AudioBufferManager/src/AudioBufferManager.h, libraries/I2S/src/I2S.cpp
Optimize AudioRquestBuffer writing when large blocks are available (i.e. I2S writes of full MP3 or AAC frames in BackgroundAudio).  Update I2S to use the new call.  Reduces 1152 calls to arb::write() to a single call/return and optimized memcpy in that case.
=> Add real block write for AudioRequestBuffer

libraries/AudioBufferManager/src/AudioBufferManager.cpp
The memcpy-version of the ABM::write updated the destination and count but neglected to move the source forward.  If a block write crossed a frame boundary then the 2nd frame would repeat the data from the first half of the buffer.
Fix by incrementing the source pointer by the same amount as was written.
=> Properly wrap AudioBufferManager block writes

libraries/PWMAudio/src/PWMAudio.cpp
I2S allows setting freq before ::begin, so allow same for PWMAudio.
=> Allow setting PWMAudio frequency before begin

libraries/ADCInput/src/ADCInput.cpp
When multiple inputs were active, the frequency was being scaled two times resulting in incorrect sampling speed.  Correct to only scale the calculation and not the stored value (which is used in `begin`).
Fixes #2754
=> Fix ADCInput clocks for multiple inputs

libraries/BluetoothAudio/src/A2DPSink.cpp, libraries/BluetoothAudio/src/A2DPSink.h
Fixes #2751
Technically a breaking change, since this PR removes Stream subclass, onTransmit method (and associated fields) and changes behavior of onConnect.
=> A2DPSink: Remove stubs, fix volume and connect callbacks

libraries/SD/src/SD.h, libraries/SDFS/src/SDFS.h
It's fixed by the PIO program and GPIO slew rates encoded in the SdFAT driver.  Remove the parameter from the SD/SDFS begins.
=> SDIO doesn't take a clock speed parameter

cores/rp2040/PIOProgram.cpp
Fixes #2768 
I've also changed `needsHigh` (`true` or `false`) to `gpioBaseNeeded` (`0` or `16`) to help simplify some of the checks and prints later on. This matches the original behavior of `PIOProgram.cpp` (at least as far as my quick test showed), though I think it may be better to change it to some kind of tertiary behavior, because GPIO base 0 and 16 are both valid for GPIO 16-31. But that's an optimization better had in a different PR, because this is just meant to be a bug fix.
=> PIOProgram: Replace __pioHighGPIO with pio_get_gpio_base()

cores/rp2040/Tone.cpp, cores/rp2040/tone2.pio, cores/rp2040/tone2.pio.h
Move `side`-setting of pin one instruction up and replace `jmp` with `.wrap` to get a 50% duty cycle.
=> Change duty cycle of PIO Tone to 50%

libraries/BTstackLib/examples/LEPeripheral/LEPeripheral.ino, libraries/LEAmDNS/src/LEAmDNS_Transfer.cpp, platform.txt, tools/platformio-build.py, variants/challenger_2040_wifi/ChallengerWiFi.cpp, variants/challenger_2040_wifi6_ble/ChallengerWiFi.cpp, variants/challenger_2040_wifi_ble/ChallengerWiFi.cpp, variants/challenger_2350_wifi6_ble5/ChallengerWiFi.cpp, variants/challenger_nb_2040_wifi/ChallengerWiFi.cpp, variants/connectivity_2040_lte_wifi_ble/Connectivity.cpp, variants/ilabs_rpico32/Ilabs2040WiFiClass.cpp
Fixes #2772
No need to set SDFAT_FILE_TYPE=3 as that is the defaulr value with upstream SdFat.  Remove it from platform.txt and platform.io build.
=> Don't set SDFAT_FILE_TYPE, default is OK

docs/i2s.rst, libraries/AudioBufferManager/src/AudioBufferManager.cpp, libraries/AudioBufferManager/src/AudioBufferManager.h, libraries/I2S/examples/I2SLoopback_Buffer/I2SLoopback_Buffer.ino, libraries/I2S/src/I2S.cpp, libraries/I2S/src/I2S.h
I quickly noticed after our discussion in https://github.com/earlephilhower/arduino-pico/pull/2775 that a buffered read was not available in the I2S library or the AudioBufferManager. I've added the necessary functionality to do this as well as a second loopback example demonstrating how to properly implement it. The documentation has also been updated with this method.
Notes:
- I have noticed performance improvements with this feature properly implemented.
- I've fixed an error in the documentation regarding the return value of `size_t I2S::write(const uint8_t *buffer, size_t size)`. I'm good with having that function and the new `size_t I2S::write(const uint8_t *buffer, size_t size)` return the number of words written. But to match the nature of the `size_t size` argument (size in …
=> Add buffer read to `AudioBufferManager` and `I2S`.

docs/platformio.rst
Addresses missing documentation issues encountered in e.g. https://github.com/earlephilhower/arduino-pico/pull/2790 but also in the PlatformIO forum.
=> Document PSRAM and Boot2 better

libraries/Wire/src/Wire.cpp
The async implementation of I2C (Wire) seems to allocate the DMA buffer for every call because the check, whether the current buffer is large enough (`if (_dmaSendBufferLen < bufLen) {`) is always `true` because `_dmaSendBufferLen` is never actually set anywhere. 
Simple fix: added a line after successful `malloc` that sets the `_dmaSendBufferLen = bufLen`. 
PS: Shouldn't we use `new uint16_t[bufLen]` here, since we're in a C++ object? It probably maps to `malloc` but it would at least avoid one cast.
=> fix: Wire::writeReadAsync always malloc'ing DMA buffer

cores/rp2040/Arduino.h, cores/rp2040/SerialPIO.h, cores/rp2040/SerialSemi.h, cores/rp2040/SerialUART.h, cores/rp2040/SerialUSB.h, cores/rp2040/posix.cpp, cores/rp2040/wiring_shift.cpp, libraries/WebServer/examples/FSBrowser/FSBrowser.ino, libraries/WiFi/src/WiFiUdp.h
Track upstream Arduino API headers
=> Move to Arduino API 10501

boards.txt, package/package_pico_index.template.json, tools/json/sparkfun_xrp_controller_beta.json, tools/makeboards.py, variants/sparkfun_xrp_controller_beta/digital.cpp, variants/sparkfun_xrp_controller_beta/init.cpp, variants/sparkfun_xrp_controller_beta/pins_arduino.h
Board definition for this: https://www.sparkfun.com/sparkfun-experiential-robotics-platform-xrp-controller.html
=> Add SparkFun XRP Controller (Beta)

libraries/SPI/src/SPIHelper.h
My application is designed to generate HSTX data on core0 in interrupts, but also uses hardware SPI for SD card access.
It turns out that the amount of time spent in `maskInterrupts`/`unmaskInterrupts` with interrupts disabled, even with an empty `_usingIRQs`, is too long.
Add a quick check and avoid touching the interrupt disable flag if there's not actually any GPIO interrupt to (un)mask.
@ladyada this fixes the hstx video glitches during SPI SD card access
=> early out of (un)maskInterrupts() if no GPIO interrupts need to be masked

libraries/BluetoothAudio/src/A2DPSource.cpp, libraries/BluetoothAudio/src/A2DPSource.h
=> A2DP: scanAsyncDone & scanAsyncResults; fix write and availableForWrite

README.md, boards.txt, package/package_pico_index.template.json, tools/json/pimoroni_servo2040.json, tools/makeboards.py, variants/pimoroni_servo2040/pins_arduino.h
Fixes #2730 .  Untested, based off of schematics
=> Add Pimoroni Servo2040

boards.txt, tools/makeboards.py
=> Add WiFi region for Pico2W

.github/workflows/pull-request.yml, cores/rp2040/tone2.pio.h, libraries/I2S/src/pio_i2s.pio.h, libraries/PDM/src/rp2040/pdm.pio, libraries/lwIP_w55rp20/src/wiznet_pio_spi.pio.h, tools/makepio.py
Ensure all PIO .pio.h headers match the .pio sources in the tree
=> Add PIO.h header verification to CI

variants/cytron_iriv_io_controller/pins_arduino.h
Added pin definitions for I2C1, even though it's not used.
Without this, the compilation failed when using the Wire library.
=> Update board variants IRIV IO Controller to add pins definition for I2C1.

cores/rp2040/RP2040Support.h, cores/rp2040/main.cpp, docs/multicore.rst
Fixes #2914
There are 2 systick units, one per core.  Set up and start core1's systick unit and track each core's epoch separately.
=> Fix rp2040.getCycleCount() from core1

cores/rp2040/SerialPIO.cpp, cores/rp2040/pio_uart.pio, cores/rp2040/pio_uart.pio.h
The SerialPIO(SoftwareSerial) receive path was convoluted and required a lot of work on the host to get the actual data out.  It also wasn't always sampling on the proper edge leading to errors whenever clocks or hold times shifted slightly.
Rewrite the SerialPIO RX path fo explicitily wait for start bit, pause 1/2 bit time, then idle for a full bit time for all bits. Takes more PIO instruction memory but works flawlessly even with mismatched clocks.
Tested with a loopback from HW UART to SW UART with a 5% clock mismatch @ 19200 baud without reception errors, whereas the original code would fail with less than a 0.5% variation.
Fixes #2928
````
#include <SoftwareSerial.h>
SoftwareSerial s(15, -1);
void setup() {
Serial1.setTX(0);
Serial1.begin(19200 + 1920/2, SERIAL_8N1);
s.begin(19200, …
```
=> Rewrite SerialPIO receive path, ensure proper edge

cores/rp2040/SerialPIO.cpp
use LUT for faster parity checks, reduces CPU load with multiple instances
=> optimize parity calculations in SerialPIO (#2932)

libraries/ADCInput/src/ADCInput.cpp
Fixes #2935
The PICO_2350A patch flipped the logic of the ADCInput bitmask calcs causing the 2040 and 2350A to use bitmasks for the 2350B (i.e. wrong GPIOs) and vice versa.
=> Fix ADCInput masking

platform.txt
Arduino OTA currently not working when its password Protected. 
adding this line enables the configuration of the Password
=> Make Arduino IDE ask for OTA password

variants/wiznet_55rp20_evb_pico/pins_arduino.h
Assigned GPIO19 to PIN_LED instead of generic 25. GPIO19 is connected to USERLED.
GPIO25 is coincidentally connected to an LED but it has other internal functions.
SPI0 generic pins are unavailable. It's use means sacrificing [other peripherals as per official pinout](https://docs.wiznet.io/Product/ioNIC/W55RP20/w55rp20-evb-pico#hardware-specification).
Assigned GPIO2 to PIN_SPI0_MISO since GPIO16 is connected to the buck-boost converted.
Assigned GPIO3 to PIN_SPI0_MOSI since GPIO19 is now defined as PIN_LED.
Assigned GPIO4 to PIN_SPI0_SCK since GPIO18 is connected to a voltage divider on VBUS.
Assigned GPIO5 to PIN_SPI0_SS since GPIO17 doesn't show up in the schematics.
=> Fixed generic PIN_LED and SPI0 Pin assignment on WIZnet W55RP20-EVB-Pico.

.github/workflows/pull-request.yml
Prevents weird update errors stemming from an already installed platform (cached), then updating some files in it manually and then pio pkg updating it.
Should fix issues seen in #2975 and other PRs.
=> Cleanly install PlatformIO platform from scratch

libraries/SerialBT/src/SerialBT.h
BT SPP doesn't have backoff and we can receive long messages.  If there's not enough memory to store them then they will be truncated.
Increase the default space to 1K to help avoid this issue.
=> Make default SerialBT FIFO 1K

libraries/AudioBufferManager/src/AudioBufferManager.cpp
Noticed in BackgroundAudio library builds, for some reason, but not in CI here.
=> Clean up ignored-qualifier warnings in ABM

boards.txt, tools/makeboards.py, tools/platformio-build.py
Now that we build the cyw43_arch as part of the core process, we need to make sure we define the flag that it uses to turn off or on the BT stack.
=> Need additional devine to get BT/BLE linked

libraries/BluetoothHIDMaster/examples/KeyboardPiano/KeyboardPiano.ino, libraries/BluetoothHIDMaster/examples/KeyboardPianoBLE/KeyboardPianoBLE.ino
Sometimes the BT or BLE announcement doesn't show up during an initial scan window.
Loop in the KeyboardPiano examples so that scans will be repeated until something actually links up.
Fixes #3074
=> Rescan if first one fails in HIDMaster examples

cores/rp2040/RP2040USB.cpp
The USB PID was already being changed depending on the devices installed in the app.  This was needed because Windows has issues with the same VID:PID exporting different HID devices (i.e. it would not recognize changed ones properly).
Unfortunately the change was to set a bit to 1 in the PID, but if the bit was already 1 then no change would occur.
Now, actually XOR the bitmap of device exports to ensure the VID:PID of a sketch with only Serial will differ from one with Serial and Keyboard, for example.
=> BREAKING: USB PID will vary depending on devices

.github/workflows/pull-request.yml
Each job was taking >12 minutes, 2x the other CI times.  Split into 4 jobs for now
=> Split build-all-variants into 4 jobs

cores/rp2040/freertos/freertos-main.cpp, cores/rp2040/lwip_wrap.cpp
Fixes #3120
LWIP was being unconditionally started under FreeRTOS, even if the app wasn't using any LWIP calls.  Now start the LWIP thread on the first call to lwip_init, same as we init the RNG.
=> Only start LWIP thread on FreeRTOS if needed

cores/rp2040/RP2040Support.h, cores/rp2040/Tone.cpp, cores/rp2040/WMath.cpp, cores/rp2040/delay.cpp, cores/rp2040/lwip_wrap.cpp, cores/rp2040/main.cpp, cores/rp2040/wiring_private.cpp, libraries/LittleFS/src/LittleFS.h, libraries/SingleFileDrive/src/SingleFileDrive.cpp
See https://github.com/earlephilhower/arduino-pico/issues/3134.  Only difference is correct error handling in one LittleFS function call when making a file passes but setting the time attribute somehow fails.
=> Clean up some add'l warnings noted

cores/rp2040/freertos/freertos-lwip.cpp, cores/rp2040/lwip_wrap.cpp, cores/rp2040/lwip_wrap.h, cores/rp2040/sdkoverride/cyw43_driver_freertos.cpp, lib/core_wrap.txt, libraries/lwIP_CYW43/src/utility/CYW43shim.cpp, libraries/lwIP_Ethernet/src/LwipIntfDev.h
Fixes #3157
Fixes #1837
The SDK's CYW43 WiFi connection scheme combined both link layer (WiFi net connection) and IP (getting an IP address from DHCP) into a single step. We worked around it with a hack wrapped function, but it resulted in the WiFi.begin() timeout being 2x as long as specified.
Remove the SDK's cyw43_arch_wifi_connect_timeout_ms and replace with our own custom CYW43::begin which will only look at the link layer. Note that the SDK docs are hokey and the cyw43_link_status is set to 1 *while network connection attempts are underway.*  This means we can't actually just look at the link state, it will be in JOIN even if it's not really joined.  So, we peek at the state internal CYW43 join FSM to see we're *really* connected.
This exposed a corner case which @ledereyes seems to …
=> Rewrite CYW43 WiFi connection scheme

cores/rp2040/USB.cpp
The old picotool interface was being added over and over each time the USB reconnected, resulting in invalid descriptors and a hang.  Make sure to remove the picotool interface on a disconnect to fix.
=> Fix picotool enabled USB descriptor

cores/rp2040/USB.cpp
Pull in latest SDK's new additional USB descriptor when in Picotool upload mode to hopefully make life easier for Windows users.
Fix interface counting in USB::findInterfaceID()
=> Add USB BOS descriptor(Picotool), fix findIntfID

libraries/LittleFS/src/LittleFS.h, libraries/SD/src/SD.h, tools/platformio-build.py, tools/uf2conv.py
CodeQL throws lots of wrong warnings, but did identify a few spots where binary &/| was used in place of boolean &&/|| and some minor Python script issues.
=> Fix minor CodeQL issues which look real

.github/workflows/pull-request.yml
GH is retiring MacOS 13 CI. recommends moving to macos-15-intel
=> Move Macx86 to MacOS 15

cores/rp2040/lwip_wrap.h
Lost an ifndef(FREERTOS) in the lwip mutex
=> Fix overzealous stripping of comments in #3181

variants/soldered_nula_rp2350/init.cpp
When creating the board variant for the Soldered Electronics NULA RP2350 board, the incorrect cyw43 pin array for the RF module was defined by mistake. My apologies.
=> Fix wrong cyw43 pin array for Soldered Electronics NULA RP2350 board

cores/rp2040/SerialUSB.cpp, cores/rp2040/SerialUSB.h, cores/rp2040/USB.cpp, cores/rp2040/USB.h, libraries/FatFSUSB/src/FatFSUSB.cpp, libraries/SingleFileDrive/src/SingleFileDrive.cpp
For simple 1-interface devices, there is a fixed position in the USB interface descriptor where the interface lives and we can hardcode an updater in the USB handler.  However, for devices like CDC(Serial) or MIDI there are multiple interfaces and the interface IDs need to be stuffed inside the actual descriptor at different locations.
To allow this, instead of just taking a fixed set of bytes and blindly patching in USB, make all interfaces do their own memcpy from a local version, updated with the new dynamic interface id, via a callback.
Add a simple USBClass callback to handle the normal 1-interface case without add'l code.
Fix MSD (SingleFileDrive, FatFSUSB) to only request the correct, single interface used.
=> Fix USB descriptors for multiple interface devices

.gitmodules, cores/rp2040/SerialUSB.cpp, cores/rp2040/USB.cpp, cores/rp2040/USB.h, tests/restyle.sh
Runs arduino_midi_library and MIDIUSB native applications on the RP2040 and RP2350 over USB
=> Add MIDIUSB-compatible library
